export const ROUTES_FRONTEND = {
  home: '/',
  health: '/health/',
  components: '/components/',
  api_testing: '/api-testing/',
  login: '/login/',
  signup: '/signup/',
  lyche: '/lyche/',
  events: '/events/',
  event: '/events/:id',
  information_page_list: '/information-page/',
  information_page_detail: '/information-page/:slugField/',
  information_page_edit: '/information-page/:slugField/edit',
  groups: '/groups/',
  admin: '/admin/',
  admin_groups: '/admin/groups/',
};
