# cypress/included:12.3.0
FROM cypress/base:18.16.0

WORKDIR /app

# Copy package file to docker.
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ /app/.yarn/

# Require up to date package.json and yarn.lock, fail otherwise.
RUN yarn install --immutable

# Copy remaining files
COPY . /app
