name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] <title>"
labels: ["feature"]
body:
- type: checkboxes
  attributes:
    label: 👀 Is there an existing feature request for this?
    description: Please search to see if a feature request already exists for the feature you are suggesting.
    options:
    - label: I have searched the existing feature requests
      required: true
- type: textarea
  attributes:
    label: 🌟 Feature statement
    description: What is your feature request? Please describe.
    placeholder: A clear and concise description of what the feature is.
  validations:
    required: true
- type: textarea
  attributes:
    label: 👨‍👩‍👦 Is the feature related to some other issue or PR?
    description: Pleas give the isse or PR-number.
    placeholder: "#issue-number" or "#PR-number"
  validations:
    required: false
- type: textarea
  attributes:
    label: 💡 Proposed Solution
    description: Describe the solution you'd like
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: 🔦 Additional Context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
- type: textarea
  attributes:
    label: 🗺️ Where on Samfundet4 do you want the feature?
    description: Pleas give a file, or general "area" of Samfundet4
  validations:
    required: true
- type: dropdown
  attributes:
    label: Priority
    description: How important is this feature to you?
    options:
      - Nice to have
      - Important
      - Critical
  validations:
    required: true
