# Generated by Django 4.1.1 on 2022-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('description_long', models.TextField()),
                ('description_short', models.TextField()),
                ('publish_dt', models.DateTimeField()),
                ('host', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
            ],
        ),
    ]
