# Generated by Django 5.0.6 on 2024-06-30 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentposition',
            name='tags',
        ),
        migrations.CreateModel(
            name='RecruitmentPositionTag',
            fields=[
                ('version', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Tags for the position', max_length=15, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recruitmentposition',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='tags associated with this position', related_name='position_tags', to='samfundet.recruitmentpositiontag'),
        ),
    ]
