# Generated by Django 5.1.9 on 2025-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_nb',
        ),
        migrations.RemoveField(
            model_name='closedperiod',
            name='message_nb',
        ),
        migrations.AddField(
            model_name='closedperiod',
            name='message_no',
            field=models.TextField(blank=True, null=True, verbose_name='Melding (norsk)'),
        ),
    ]
