# Generated by Django 5.1.9 on 2025-12-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
