# Generated by Django 5.0.2 on 2024-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentseparateposition",
            name="description_en",
            field=models.CharField(
                blank=True,
                help_text="Short description of the position (EN)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recruitmentseparateposition",
            name="description_nb",
            field=models.CharField(
                blank=True,
                help_text="Short description of the position (NB)",
                max_length=100,
                null=True,
            ),
        ),
    ]
