# Generated by Django 5.0.2 on 2024-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentstatistics",
            name="average_applicant_applications",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gang diversity"
            ),
        ),
        migrations.AddField(
            model_name="recruitmentstatistics",
            name="average_gang_diversity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gang diversity"
            ),
        ),
        migrations.AddField(
            model_name="recruitmentstatistics",
            name="total_accepted",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total accepted applicants"
            ),
        ),
        migrations.AddField(
            model_name="recruitmentstatistics",
            name="total_withdrawn",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total Withdrawn applications"
            ),
        ),
    ]
