# Generated by Django 4.1.1 on 2022-10-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_long',
            new_name='description_long_en',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_short',
            new_name='description_long_no',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='event',
            name='description_short_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_short_no',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_no',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='samfundet.eventgroup'),
            preserve_default=False,
        ),
    ]
