# Generated by Django 4.1.1 on 2022-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('last_renovated', models.IntegerField()),
                ('designed_for_handicapped', models.BooleanField()),
                ('responsible_crew', models.CharField(max_length=140)),
            ],
        ),
    ]
