# Generated by Django 5.0.7 on 2024-07-22 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimeblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Block date')),
                ('start_dt', models.DateTimeField(help_text='Block start time')),
                ('end_dt', models.DateTimeField(help_text='Block end time')),
                ('rating', models.FloatField(help_text='Rating used for optimizing interview time')),
                ('available_interviewers', models.ManyToManyField(blank=True, help_text='Interviewers in this time block', related_name='interview_timeblocks', to=settings.AUTH_USER_MODEL)),
                ('recruitment_position', models.ForeignKey(help_text='The position which is recruiting', on_delete=django.db.models.deletion.CASCADE, related_name='interview_timeblocks', to='samfundet.recruitmentposition')),
            ],
        ),
    ]
