# Generated by Django 5.0.6 on 2024-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='doors_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
