# Generated by Django 5.0.2 on 2024-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentapplication",
            name="recruiter_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Set"),
                    (1, "Called and Accepted"),
                    (2, "Called and Rejected"),
                    (3, "Rejection"),
                    (4, "Automatic Rejection"),
                ],
                default=0,
                help_text="The status of the application",
            ),
        ),
    ]
