# Generated by Django 5.0 on 2023-12-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="recruiter_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Set"),
                    (1, "Called and Accepted"),
                    (2, "Called and Rejected"),
                    (3, "Automatic Rejection"),
                ],
                default=0,
                help_text="The status of the admission",
            ),
        ),
    ]
