# Generated by Django 5.0 on 2023-12-28 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentStatistics",
            fields=[
                (
                    "recruitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="statistics",
                        serialize=False,
                        to="samfundet.recruitment",
                    ),
                ),
                (
                    "total_applicants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total applicants"
                    ),
                ),
                (
                    "total_admissions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total admissions"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
