# Generated by Django 5.1.14 on 2026-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('art', 'Kunst'), ('concert', 'Konsert'), ('course', 'Kurs'), ('debate', 'Debatt'), ('dj', 'DJ'), ('excenteraften', 'Excenteraften'), ('football_match', 'Fotballkamp'), ('happening', 'Happening'), ('lecture', 'Forelesning'), ('luka_event', 'LUKA-arrangement'), ('meeting', 'Møte'), ('movie', 'Film'), ('music', 'Musikk'), ('party_meeting', 'Festmøte'), ('performance', 'Performance'), ('quiz', 'Quiz'), ('samfundet_meeting', 'Samfundsmøte'), ('show', 'Show'), ('theater', 'Teater'), ('theme_party', 'Temafest'), ('uka_event', 'UKE-arrangement'), ('other', 'Annet')], default='other', max_length=30),
        ),
    ]
