# Generated by Django 5.1.1 on 2024-09-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_role_usergangrole_usergangsectionrole_userorgrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gang',
            name='event_admin_group',
        ),
        migrations.RemoveField(
            model_name='gang',
            name='gang_leader_group',
        ),
        migrations.RemoveField(
            model_name='gang',
            name='recruitment_admin_group',
        ),
    ]
