# Generated by Django 5.0 on 2023-12-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_nb", models.CharField(max_length=64, unique=True)),
                ("name_en", models.CharField(max_length=64, unique=True)),
                ("abbreviation", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="samfundet.campus",
            ),
        ),
    ]
