# Generated by Django 5.0 on 2024-01-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="informationpage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="informationpage",
            name="version",
            field=models.PositiveIntegerField(
                blank=True, default=0, editable=False, null=True
            ),
        ),
    ]
