# Generated by Django 5.1.9 on 2025-10-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_remove_closedperiod_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedperiod',
            old_name='message_no',
            new_name='message_nb',
        ),
    ]
