# Generated by Django 5.0 on 2023-12-31 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Navn (norsk)"
                    ),
                ),
                (
                    "description_nb",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Beskrivelse (norsk)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Navn (engelsk)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Beskrivelse (engelsk)"
                    ),
                ),
                ("base_price", models.PositiveSmallIntegerField(blank=True)),
                ("released_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samfundet.image",
                        verbose_name="Produkt Bilde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merch",
                "verbose_name_plural": "Merch",
            },
        ),
        migrations.CreateModel(
            name="MerchVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        max_length=16, verbose_name="Variation specification"
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Price Variation"
                    ),
                ),
                (
                    "stock",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="In stock"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "merch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="samfundet.merch",
                        verbose_name="Merch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
