# Generated by Django 5.0.2 on 2024-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_alter_recruitmentapplication_recruiter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='promo_media',
            field=models.CharField(help_text='Youtube video id', max_length=12, null=True),
        ),
    ]
