# Generated by Django 5.0 on 2023-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentadmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="recruitmentadmission",
            name="withdrawn",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
