# Generated by Django 5.0 on 2023-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0003_rename_date_reservation_reservation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(verbose_name="Dato"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(verbose_name="Starttid"),
        ),
    ]
