# Generated by Django 4.1.1 on 2022-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0003_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_group',
            field=models.CharField(
                choices=[('INCLUDED', 'Included with entrance'), ('FREE', 'Free'), ('BILLIG', 'Paid'), ('REGISTRATION', 'Free with registration')],
                default='FREE',
                max_length=30
            ),
        ),
    ]
