# Generated by Django 5.0 on 2023-12-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0003_recruitmentstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentstatistics",
            name="recruitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="statistics",
                serialize=False,
                to="samfundet.recruitment",
            ),
        ),
    ]
