# Generated by Django 5.1.9 on 2026-02-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mdb_medlem_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='medlem_id in mdb2'),
        ),
    ]
