# Generated by Django 4.1.6 on 2023-02-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0003_textitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textitem',
            options={'verbose_name': 'TextItem', 'verbose_name_plural': 'TextItems'},
        ),
    ]
