# Generated by Django 5.1.1 on 2024-09-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_interviewtimeblock'),
        ('samfundet', '0003_remove_gang_event_admin_group_and_more'),
    ]

    operations = [
    ]
