# Generated by Django 4.1.7 on 2023-03-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0004_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'permissions': [('set_opened', 'Can set the opening hours of a venue')], 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
    ]
