# Generated by Django 5.0.2 on 2024-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0004_alter_recruitment_promo_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='promo_media',
            field=models.CharField(default=None, help_text='Youtube video id', max_length=11, null=True),
        ),
    ]
