# Generated by Django 5.1.1 on 2024-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0004_campus_total_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentpositionsharedinterviewgroup",
            name="name_en",
            field=models.CharField(
                default="hello",
                help_text="Name of the recruitmentgroup (EN)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpositionsharedinterviewgroup",
            name="name_nb",
            field=models.CharField(
                default="hello",
                help_text="Name of the recruitmentgroup (NB)",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
