# Generated by Django 5.0 on 2024-01-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0004_campus_user_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age_restriction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Ingen aldersgrense"),
                    ("eighteen", "18 år"),
                    ("twenty", "20 år"),
                    ("mixed", "18 år (student), 20 år (ikke-student)"),
                ],
                default=None,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("samfundsmote", "Samfundsmøte"),
                    ("concert", "Konsert"),
                    ("debate", "Debatt"),
                    ("quiz", "Quiz"),
                    ("lecture", "Kurs"),
                    ("other", "Annet"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_long_en",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_long_nb",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_short_en",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_short_nb",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="samfundet.image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="event",
            name="publish_dt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_dt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Aktiv"),
                    ("archived", "Arkivert"),
                    ("cancelled", "Avlyst"),
                    ("deleted", "Slettet"),
                ],
                default="active",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("included", "Included with entrance"),
                    ("free", "Free"),
                    ("billig", "Paid"),
                    ("registration", "Free with registration"),
                    ("custom", "Custom"),
                ],
                default="free",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_en",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_nb",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
