# Generated by Django 5.2.11 on 2026-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0004_user_mdb_medlem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedlemsInfo',
            fields=[
                ('medlem_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fornavn', models.CharField(blank=True, null=True)),
                ('etternavn', models.CharField(blank=True, null=True)),
                ('fodselsdato', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, null=True)),
                ('skole', models.CharField(blank=True, null=True)),
                ('studie', models.CharField(blank=True, null=True)),
                ('brukernavn', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'MedlemsInfo',
                'db_table': 'lim_medlemsinfo',
                'managed': False,
            },
        ),
    ]
