# Generated by Django 5.0 on 2024-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0004_campus_user_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentadmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="recruitmentadmission",
            name="withdrawn",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
