# Generated by Django 4.1.7 on 2023-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_alter_venue_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='opening',
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_friday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_monday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_saturday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_sunday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_thursday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_tuesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_wednesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
