# Generated by Django 5.2.11 on 2026-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_medlemsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='general_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lastfm_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='soundcloud_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vimeo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_embed',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
