# Generated by Django 4.1.7 on 2023-03-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_textitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('samfundsmote', 'Samfundsmøte'), ('concert', 'Konsert'), ('debate', 'Debatt'), ('quiz', 'Quiz'), ('lecture', 'Kurs'), ('other', 'Annet')], default='other', max_length=30),
        ),
    ]
