# Generated by Django 5.1.1 on 2024-09-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_role_content_type_role_created_at_role_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentposition',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section that is recruiting', null=True, on_delete=django.db.models.deletion.CASCADE, to='samfundet.gangsection'),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='gang',
            field=models.ForeignKey(blank=True, help_text='The gang that is recruiting', null=True, on_delete=django.db.models.deletion.CASCADE, to='samfundet.gang'),
        ),
    ]
