# Generated by Django 5.2.12 on 2026-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_medlemsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilligPurchase',
            fields=[
                ('id', models.IntegerField(db_column='purchase', primary_key=True, serialize=False)),
                ('owner_member_id', models.IntegerField(blank=True, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'BilligPurchase',
                'verbose_name_plural': 'BilligPurchases',
                'db_table': 'billig.purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligTicket',
            fields=[
                ('id', models.IntegerField(db_column='ticket', primary_key=True, serialize=False)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('refunded', models.DateTimeField(blank=True, null=True)),
                ('on_card', models.BooleanField()),
                ('refunder', models.TextField(blank=True, null=True)),
                ('point_of_refund', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BilligTicket',
                'verbose_name_plural': 'BilligTickets',
                'db_table': 'billig.ticket',
                'managed': False,
            },
        ),
    ]
