# Generated by Django 5.0 on 2024-01-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0005_blogpost_created_by_blogpost_updated_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="date",
            new_name="reservation_date",
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="samfundet.table",
                verbose_name="Bord",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="samfundet.venue",
                verbose_name="Sted",
            ),
        ),
    ]
