# Generated by Django 5.1.1 on 2024-09-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0004_merge_20240924_0058'),
        ('samfundet', '0005_role_content_type_role_created_at_role_created_by_and_more'),
    ]

    operations = [
    ]
