# Generated by Django 5.0.7 on 2024-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_purchasefeedbackmodel_purchasefeedbackalternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='doors_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
