# Generated by Django 5.2.10 on 2026-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_medlemsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='closed_override',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
