# Generated by Django 5.2.12 on 2026-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0005_medlemsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mdb_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last updated from mdb'),
        ),
    ]
