# Generated by Django 5.2.11 on 2026-04-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_userpreference_closed_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='closed_override',
            field=models.CharField(choices=[('default', 'Default'), ('closed', 'Closed'), ('open', 'Open')], default='default', max_length=30),
        ),
    ]
