# Generated by Django 5.1.1 on 2024-10-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_recruitmentposition_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='color',
            field=models.CharField(max_length=15, verbose_name='Farge på boks (hex color eller CSS-constant)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.image', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='text_en',
            field=models.CharField(max_length=255, verbose_name='Tekst (engelsk)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='text_nb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tekst (norsk)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='title_en',
            field=models.CharField(max_length=60, verbose_name='Tittel (engelsk)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='title_nb',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Tittel (norsk)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
