# Generated by Django 5.0 on 2024-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0006_rename_date_reservation_reservation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentadmission",
            name="withdrawn",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
