# Generated by Django 5.0.1 on 2024-01-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samfundet", "0006_rename_date_reservation_reservation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="foodcategory", name="created_by",),
        migrations.RemoveField(model_name="foodcategory", name="updated_by",),
        migrations.RemoveField(model_name="menuitem", name="food_category",),
        migrations.RemoveField(model_name="foodpreference", name="created_by",),
        migrations.RemoveField(model_name="foodpreference", name="updated_by",),
        migrations.RemoveField(model_name="menuitem", name="food_preferences",),
        migrations.RemoveField(model_name="menu", name="created_by",),
        migrations.RemoveField(model_name="menu", name="menu_items",),
        migrations.RemoveField(model_name="menu", name="updated_by",),
        migrations.RemoveField(model_name="menuitem", name="created_by",),
        migrations.RemoveField(model_name="menuitem", name="updated_by",),
        migrations.RemoveField(model_name="reservation", name="created_by",),
        migrations.RemoveField(model_name="reservation", name="table",),
        migrations.RemoveField(model_name="reservation", name="updated_by",),
        migrations.RemoveField(model_name="reservation", name="user",),
        migrations.RemoveField(model_name="reservation", name="venue",),
        migrations.RemoveField(model_name="table", name="created_by",),
        migrations.RemoveField(model_name="table", name="updated_by",),
        migrations.RemoveField(model_name="table", name="venue",),
        migrations.DeleteModel(name="Booking",),
        migrations.DeleteModel(name="FoodCategory",),
        migrations.DeleteModel(name="FoodPreference",),
        migrations.DeleteModel(name="Menu",),
        migrations.DeleteModel(name="MenuItem",),
        migrations.DeleteModel(name="Reservation",),
        migrations.DeleteModel(name="Table",),
    ]
