# Generated by Django 5.2.12 on 2026-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_billigpurchase_billigticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilligPaymentError',
            fields=[
                ('error', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failed', models.DateTimeField(blank=True, null=True)),
                ('owner_cardno', models.CharField(blank=True, max_length=140, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'BilligPaymentError',
                'verbose_name_plural': 'BilligPaymentErrors',
                'db_table': 'billig.payment_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligTicketCard',
            fields=[
                ('card', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner_member_id', models.IntegerField(blank=True, null=True)),
                ('membership_ends', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BilligTicketCard',
                'verbose_name_plural': 'BilligTicketCards',
                'db_table': 'billig.ticket_card',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='billigevent',
            table='billig.event_lim_web',
        ),
    ]
