# Generated by Django 4.1.3 on 2022-11-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GangType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Gruppetype')),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Navn')),
                ('abbreviation', models.CharField(max_length=64, verbose_name='Forkortelse')),
                ('webpage', models.URLField(verbose_name='Nettside')),
                ('group_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samfundet.gangtype', verbose_name='Gruppetype')),
            ],
        ),
    ]
