# Generated by Django 4.2.7 on 2024-01-16 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_rename_date_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for the interview', related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
