# Generated by Django 5.0.8 on 2024-09-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0002_remove_recruitmentposition_tags_and_more'),
        ('samfundet', '0007_recruitmentgangstat'),
    ]

    operations = [
    ]
