# Generated by Django 5.1.1 on 2024-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0007_alter_infobox_color_alter_infobox_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentpositionsharedinterviewgroup",
            name="name_en",
            field=models.CharField(
                default="hi",
                help_text="Name of the recruitmentgroup (EN)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpositionsharedinterviewgroup",
            name="name_nb",
            field=models.CharField(
                default="hi",
                help_text="Name of the recruitmentgroup (NB)",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
