# Generated by Django 5.2.15 on 2026-06-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_billigpaymenterror_billigticketcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='cursor_trail',
        ),
    ]
