# Generated by Django 5.0 on 2024-02-08 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0007_recruitmentadmission_withdrawn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
