# Generated by Django 5.0 on 2024-02-02 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0007_recruitmentadmission_withdrawn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="version",
        ),
    ]
