# Generated by Django 5.1.1 on 2024-10-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0006_merge_20240925_1842'),
        ('samfundet', '0007_alter_infobox_color_alter_infobox_image_and_more'),
    ]

    operations = [
    ]
