# Generated by Django 4.1.7 on 2023-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_remove_event_banner_image_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_nb',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='slug_field',
            field=models.SlugField(blank=True, help_text='Primary key, this field will identify the object and be used in the URL.', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
