# Generated by Django 5.0 on 2024-02-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_recruitmentadmission_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='end_dt',
            field=models.DateTimeField(help_text='End of occupied time'),
        ),
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='recruitment',
            field=models.ForeignKey(help_text='Which recruitment this occupancy applies to', on_delete=django.db.models.deletion.CASCADE, to='samfundet.recruitment'),
        ),
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='start_dt',
            field=models.DateTimeField(help_text='Start of occupied time'),
        ),
    ]
