# Generated by Django 4.2.7 on 2024-01-18 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_interview_interviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for this interview', related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
