# Generated by Django 5.1.1 on 2024-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_alter_infobox_color_alter_infobox_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='promo_media',
            field=models.CharField(blank=True, default=None, help_text='Youtube video id', max_length=11, null=True),
        ),
    ]
