# Generated by Django 5.1.1 on 2024-11-02 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_alter_infobox_color_alter_infobox_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='applicant_priority',
            field=models.PositiveIntegerField(blank=True, help_text='Applicant priority of the position(recruitment_position) to which this application related.', null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='applicant_state',
            field=models.IntegerField(choices=[(0, 'Unprocessed by all above on priority'), (1, 'Highest priority, and reserve'), (2, 'Highest priority, and wanted'), (3, 'Another position has this on reserve, with higher priority'), (4, 'Another position has this on reserve, with higher priority, but you have reserved'), (5, 'Another position has this on reserve, with higher priority, but you have them as wanted'), (6, 'Another position has this on reserve, with higher priority'), (7, 'Another position has this on wanted, with higher priority, but you have reserved'), (8, 'Another position has this on wanted, with higher priority, but you have them as wanted'), (10, 'Other position has priority')], default=0, help_text="Recruiter's view of the applicant's status."),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='application_text',
            field=models.TextField(help_text='Motivation text submitted by the applicant'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='interview',
            field=models.ForeignKey(blank=True, help_text='Interview associated with this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='samfundet.interview'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruiter_priority',
            field=models.IntegerField(choices=[(0, 'Not Set'), (1, 'Reserve'), (2, 'Wanted'), (3, 'Not Wanted')], default=0, help_text="Recruiter's priority for this application."),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruiter_status',
            field=models.IntegerField(choices=[(0, 'Not Set'), (1, 'Called and Accepted'), (2, 'Called and Rejected'), (3, 'Rejection'), (4, 'Automatic Rejection')], default=0, help_text='Current status of this application.'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruitment',
            field=models.ForeignKey(help_text='Recruitment to which this application is related.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='samfundet.recruitment'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruitment_position',
            field=models.ForeignKey(help_text='Position to which this application is related.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='samfundet.recruitmentposition'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='user',
            field=models.ForeignKey(help_text='User who submitted this application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
