# Generated by Django 5.2.11 on 2026-04-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0007_alter_userpreference_closed_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='closed_override',
        ),
    ]
