# Generated by Django 4.1.7 on 2023-03-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_remove_event_codeword_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('debug', 'Can view debug mode')]},
        ),
    ]
