# Generated by Django 5.0.2 on 2024-03-05 18:35

import samfundet.models.utils.recruitment_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_alter_recruitmentadmission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentadmission',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Applicant file', null=True, upload_to=samfundet.models.utils.recruitment_filename.upload_file_recruitment_path, verbose_name='Applicant file'),
        ),
        migrations.AddField(
            model_name='recruitmentadmission',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Applicant image', null=True, upload_to=samfundet.models.utils.recruitment_filename.upload_file_recruitment_path, verbose_name='Applicant image'),
        ),
    ]
