# Generated by Django 4.1.3 on 2022-11-23 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samfundet', '0008_informationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('theme-light', 'Light'), ('theme-dark', 'Dark')], default='theme-light', max_length=30),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
