# Generated by Django 5.2.15 on 2026-06-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_remove_userpreference_cursor_trail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='mirror_dimension',
        ),
    ]
