# Generated by Django 5.1.1 on 2024-11-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_alter_recruitmentapplication_applicant_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruiter_priority',
            field=models.IntegerField(choices=[(0, 'Not Set'), (1, 'Reserve'), (2, 'Wanted'), (3, 'Not Wanted')], default=0, help_text="Recruiter's priority for this application - should not be visible to applicant"),
        ),
    ]
