# Generated by Django 5.1.1 on 2024-10-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_merge_20241018_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewTimeblock',
        ),
    ]
