# Generated by Django 5.0.2 on 2024-02-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0008_alter_recruitmentadmission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="applicant_priority",
            field=models.IntegerField(
                blank=True, help_text="The priority of the admission", null=True
            ),
        ),
    ]
