# Generated by Django 5.0.2 on 2024-02-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samfundet", "0009_alter_recruitmentadmission_applicant_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedBackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("path", models.CharField(blank=True, max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("device_headers", models.CharField(blank=True, max_length=255)),
                ("screen_resolution", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(max_length=254, null=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "POSITIVE"),
                            ("NEGATIVE", "NEGATIVE"),
                            ("MIX", "MIX"),
                            ("OTHER", "OTHER"),
                        ],
                        default="POSITIVE",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "UserFeedBack",},
        ),
    ]
