# Generated by Django 5.1.1 on 2024-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0009_recruitmentpositionsharedinterviewgroup_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='promo_media',
            field=models.CharField(blank=True, default=None, help_text='Youtube video id', max_length=11, null=True),
        ),
    ]
