# Generated by Django 4.1.7 on 2023-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedperiod',
            options={'verbose_name': 'ClosedPeriod', 'verbose_name_plural': 'ClosedPeriods'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'FoodCategory', 'verbose_name_plural': 'FoodCategories'},
        ),
        migrations.AlterModelOptions(
            name='foodpreference',
            options={'verbose_name': 'FoodPreference', 'verbose_name_plural': 'FoodPreferences'},
        ),
        migrations.AlterModelOptions(
            name='saksdokument',
            options={'verbose_name': 'Saksdokument', 'verbose_name_plural': 'Saksdokumenter'},
        ),
    ]
