# Generated by Django 5.1.1 on 2024-12-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0010_recruitment_promo_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="gangtype",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gangtypes",
                to="samfundet.organization",
                verbose_name="Organisasjon",
            ),
        ),
    ]
