# Generated by Django 5.1.1 on 2024-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0010_recruitment_promo_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentposition",
            name="file_description_en",
            field=models.TextField(
                blank=True, help_text="Description of file needed (EN)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="file_description_nb",
            field=models.TextField(
                blank=True, help_text="Description of file needed (NB)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="has_file_upload",
            field=models.BooleanField(
                default=False, help_text="Does position have file upload"
            ),
        ),
    ]
