# Generated by Django 5.0.2 on 2024-03-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0010_userfeedbackmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="info_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="samfundet.informationpage",
                verbose_name="Infoside",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="info_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="samfundet.informationpage",
                verbose_name="Infoside",
            ),
        ),
    ]
