# Generated by Django 5.1.1 on 2024-12-09 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0010_recruitment_promo_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitment",
            old_name="reprioritization_deadline_for_groups",
            new_name="reprioritization_deadline_for_gangs",
        ),
    ]
