# Generated by Django 5.0.2 on 2024-02-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samfundet", "0010_userfeedbackmodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="userfeedbackmodel", name="feedback_type",),
    ]
