# Generated by Django 5.0.2 on 2024-04-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0011_merch_merchvariation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_applicants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total applicants"
                    ),
                ),
                (
                    "total_admissions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total admissions"
                    ),
                ),
                (
                    "recruitment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="samfundet.recruitment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
