# Generated by Django 5.2.15 on 2026-07-03 22:59

import samfundet.models.general
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_large',
            field=models.ImageField(blank=True, editable=False, upload_to=samfundet.models.general.image_upload_path),
        ),
        migrations.AddField(
            model_name='image',
            name='image_medium',
            field=models.ImageField(blank=True, editable=False, upload_to=samfundet.models.general.image_upload_path),
        ),
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.ImageField(blank=True, editable=False, upload_to=samfundet.models.general.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=samfundet.models.general.image_upload_path),
        ),
        migrations.AlterField(
            model_name='saksdokument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='saksdokument/'),
        ),
    ]
