# Generated by Django 5.1.1 on 2024-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0011_recruitmentposition_file_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recruitment_is_open_to_other_positions",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Is open to other positions in recruitment",
            ),
        ),
    ]
