# Generated by Django 5.0.2 on 2024-04-11 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0011_merch_merchvariation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="version",
        ),
    ]
