# Generated by Django 5.0.2 on 2024-04-25 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0011_merch_merchvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for this interview', related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
