# Generated by Django 4.1.7 on 2023-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0011_alter_closedperiod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name': 'KeyValue',
                'verbose_name_plural': 'KeyValues',
            },
        ),
    ]
