# Generated by Django 5.0.2 on 2024-04-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0011_merch_merchvariation'),
        ('samfundet', '0011_purchasefeedbackmodel_purchasefeedbackalternative_and_more'),
    ]

    operations = [
    ]
