# Generated by Django 5.0.2 on 2024-04-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0012_merge_20240411_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasefeedbackmodel',
            options={'verbose_name': 'PurchaseFeedback'},
        ),
    ]
