# Generated by Django 4.1.7 on 2023-04-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0012_keyvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPriceCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonMemberEmailRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='price_group',
            field=models.CharField(blank=True, choices=[('INCLUDED', 'Included with entrance'), ('FREE', 'Free'), ('BILLIG', 'Paid'), ('REGISTRATION', 'Free with registration'), ('CUSTOM', 'Custom')], default='FREE', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_emails', models.ManyToManyField(blank=True, null=True, to='samfundet.nonmemberemailregistration')),
                ('registered_users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='custom_tickets',
            field=models.ManyToManyField(blank=True, null=True, to='samfundet.eventpricecustom'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.eventregistration'),
        ),
    ]
