# Generated by Django 4.1.3 on 2022-11-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samfundet', '0012_alter_gang_abbreviation_alter_gang_group_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'verbose_name': 'EventGroup', 'verbose_name_plural': 'EventGroups'},
        ),
        migrations.AlterModelOptions(
            name='gang',
            options={'verbose_name': 'Gang', 'verbose_name_plural': 'Gangs'},
        ),
        migrations.AlterModelOptions(
            name='gangtype',
            options={'verbose_name': 'GangType', 'verbose_name_plural': 'GangTypes'},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'InformationPage', 'verbose_name_plural': 'InformationPages'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'UserPreference', 'verbose_name_plural': 'UserPreferences'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
