# Generated by Django 4.1.7 on 2023-04-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0013_eventpricecustom_nonmemberemailregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.eventregistration'),
        ),
        migrations.AlterField(
            model_name='nonmemberemailregistration',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
