# Generated by Django 5.1.1 on 2025-01-19 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0013_gangtype_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitment",
            old_name="reprioritization_deadline_for_groups",
            new_name="reprioritization_deadline_for_gangs",
        ),
    ]
