# Generated by Django 5.0.2 on 2024-04-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0013_alter_purchasefeedbackmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasefeedbackalternative',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackalternative',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackalternative',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackalternative',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackalternative',
            name='version',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchasefeedbackmodel',
            name='version',
        ),
    ]
