# Generated by Django 5.2.15 on 2026-07-11 13:37

import samfundet.models.general
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0013_tag_name_case_insensitive_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saksdokument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=samfundet.models.general.saksdokument_upload_path),
        ),
    ]
