# Generated by Django 5.0.2 on 2024-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0014_gangsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="orglogos/", verbose_name="Logo"
            ),
        ),
    ]
