# Generated by Django 4.1.3 on 2022-11-26 23:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samfundet', '0014_venue_closing_venue_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_long_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_long_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.eventgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_group',
            field=models.CharField(blank=True, choices=[('INCLUDED', 'Included with entrance'), ('FREE', 'Free'), ('BILLIG', 'Paid'), ('REGISTRATION', 'Free with registration')], default='FREE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gang',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Forkortelse'),
        ),
        migrations.AlterField(
            model_name='gang',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='gangtype',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Gruppetype'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn Engelsk'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='name_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn Norsk'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst Engelsk'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='text_no',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst Norsk'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel Engelsk'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel Norsk'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('theme-light', 'Light'), ('theme-dark', 'Dark')], default='theme-light', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='closing',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='handicapped_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='last_renovated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='responsible_crew',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
