# Generated by Django 5.0.6 on 2024-05-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0014_gangsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentTimeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.PositiveIntegerField(verbose_name="Time")),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
    ]
