# Generated by Django 5.0.2 on 2024-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0014_gangsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="applicant_priority",
            field=models.PositiveIntegerField(
                blank=True, help_text="The priority of the admission", null=True
            ),
        ),
    ]
