# Generated by Django 5.2.15 on 2026-08-08 08:09

import django.db.models.deletion
import samfundet.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('samfundet', '0014_alter_saksdokument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gang',
            name='info_page',
        ),
        migrations.DeleteModel(
            name='InformationPage',
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    'slug_field',
                    samfundet.fields.LowerCaseSlugField(
                        blank=True, help_text='Identifies the object and is used in the URL. Always lowercase.', max_length=64, unique=True
                    ),
                ),
                ('visible', models.BooleanField(default=True, help_text='If the information page is publicly viewable')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'gang',
                    models.ForeignKey(
                        blank=True,
                        help_text='Owner of the information page',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owned_info_pages',
                        to='samfundet.gang',
                    ),
                ),
                (
                    'section',
                    models.ForeignKey(
                        blank=True,
                        help_text='Owner of the information page',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owned_info_pages',
                        to='samfundet.gangsection',
                    ),
                ),
            ],
            options={
                'verbose_name': 'InformationPage',
                'verbose_name_plural': 'InformationPages',
            },
        ),
        migrations.CreateModel(
            name='InformationPageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Revision number, starts at 1 and increments for every content edit')),
                ('title_nb', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (norsk)')),
                ('text_nb', models.TextField(blank=True, null=True, verbose_name='Tekst (norsk)')),
                ('title_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (engelsk)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Tekst (engelsk)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='samfundet.informationpage')),
            ],
            options={
                'verbose_name': 'InformationPageRevision',
                'verbose_name_plural': 'InformationPageRevisions',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='informationpage',
            name='current_revision',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='samfundet.informationpagerevision',
            ),
        ),
        migrations.AddField(
            model_name='gang',
            name='info_page',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='samfundet.informationpage',
                verbose_name='Infoside',
            ),
        ),
        migrations.AddConstraint(
            model_name='informationpage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('gang__isnull', False), ('section__isnull', True)),
                    models.Q(('gang__isnull', True), ('section__isnull', False)),
                    _connector='OR',
                ),
                name='informationpage_exactly_one_owner',
                violation_error_message='Information page must be owned by either a gang or a section, not both',
            ),
        ),
        migrations.AddConstraint(
            model_name='informationpagerevision',
            constraint=models.UniqueConstraint(fields=('page', 'version'), name='unique_information_page_revision_version'),
        ),
    ]
