# Generated by Django 5.1.1 on 2025-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "samfundet",
            "0014_rename_reprioritization_deadline_for_groups_recruitment_reprioritization_deadline_for_gangs",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recruitment_is_open_to_other_positions",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Is open to other positions in recruitment",
            ),
        ),
    ]
