# Generated by Django 5.1.1 on 2025-01-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "samfundet",
            "0014_rename_reprioritization_deadline_for_groups_recruitment_reprioritization_deadline_for_gangs",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentPositionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repriorization_value",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Collected value of repriorization (after interview)",
                    ),
                ),
                (
                    "repriorization_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Amount of repriorizations (after interview)",
                    ),
                ),
                (
                    "withdrawn_rate",
                    models.FloatField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Collected value of repriorization (after interview)",
                    ),
                ),
                (
                    "recruitment_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_stats",
                        to="samfundet.recruitmentposition",
                    ),
                ),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
    ]
