# Generated by Django 5.0.2 on 2024-06-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0014_gangsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentadmission",
            name="applicant_state",
            field=models.IntegerField(
                choices=[
                    (0, "Unprocessed by all"),
                    (1, "Wanted by other, higher prioritization, wanted"),
                    (2, "Wanted by other, higher prioritization, wanted"),
                    (3, "Wanted by other, higher prioritization, wanted"),
                    (4, "Wanted by other, higher prioritization, wanted"),
                    (5, "Wanted by other, higher prioritization, wanted"),
                    (6, "Wanted by other, higher prioritization, wanted"),
                    (7, "Wanted by other, higher prioritization, wanted"),
                    (8, "Wanted by other, higher prioritization, wanted"),
                ],
                default=0,
                help_text="The state of the applicant for the recruiter",
            ),
        ),
    ]
