# Generated by Django 5.0.2 on 2024-06-09 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0014_gangsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Interviewers for this interview",
                null=True,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
