# Generated by Django 5.1.1 on 2025-02-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0014_rename_reprioritization_deadline_for_groups_recruitment_reprioritization_deadline_for_gangs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentposition',
            name='default_application_letter_nb',
            field=models.TextField(blank=True, help_text='Default application letter for the position', null=True),
        ),
    ]
