# Generated by Django 5.0.2 on 2024-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0014_remove_purchasefeedbackalternative_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasefeedbackalternative',
            name='selected',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='purchasefeedbackalternative',
            unique_together={('form', 'alternative')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasefeedbackquestion',
            unique_together={('form', 'question')},
        ),
    ]
