# Generated by Django 5.0.2 on 2024-04-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0015_alter_purchasefeedbackalternative_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasefeedbackmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samfundet.event'),
        ),
        migrations.AlterField(
            model_name='purchasefeedbackmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasefeedbackquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
