# Generated by Django 5.1.1 on 2025-02-13 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0015_alter_recruitmentposition_default_application_letter_nb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="version",
        ),
    ]
