# Generated by Django 5.2.15 on 2026-08-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0008_remove_userpreference_closed_override'),
        ('samfundet', '0015_remove_informationpage_text_en_and_more'),
    ]

    operations = [
    ]
