# Generated by Django 4.1.3 on 2022-11-26 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0015_alter_event_description_long_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn Norsk')),
                ('description_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel Norsk')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn Engelsk')),
                ('description_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel Engelsk')),
                ('seating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_friday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_monday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_saturday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_sunday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_thursday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_tuesday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_wednesday',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_friday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_monday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_saturday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_sunday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_thursday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_tuesday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_wednesday',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
