# Generated by Django 5.0.2 on 2024-06-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0015_alter_recruitmentadmission_applicant_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="max_admissions",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Max admissions per applicant"
            ),
        ),
    ]
