# Generated by Django 4.1.7 on 2023-04-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0015_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status_group',
        ),
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('None', 'Ingen aldersgrense'), ('eighteen', '18 år'), ('twenty', '20 år'), ('mixed', '18 år (student), 20 år (ikke-student)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktiv'), ('archived', 'Arkivert'), ('cancelled', 'Avlyst'), ('deleted', 'Slettet')], default='active', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_group',
            field=models.CharField(blank=True, choices=[('included', 'Included with entrance'), ('free', 'Free'), ('billig', 'Paid'), ('registration', 'Free with registration'), ('custom', 'Custom')], default='free', max_length=30, null=True),
        ),
    ]
