# Generated by Django 5.0.6 on 2024-05-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0015_recruitmenttimestat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmenttimestat",
            name="recruitment_stats",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_stats",
                to="samfundet.recruitmentstatistics",
            ),
        ),
    ]
