# Generated by Django 5.0.2 on 2024-06-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0015_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentposition",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that is recruiting",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="samfundet.organization",
            ),
        ),
    ]
