# Generated by Django 5.0.6 on 2024-05-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0016_alter_recruitmenttimestat_recruitment_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentDateStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Time")),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
    ]
