# Generated by Django 5.0.2 on 2024-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0016_recruitment_max_admissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentadmission",
            name="applicant_state",
            field=models.IntegerField(
                choices=[
                    (0, "Unprocessed by all above on priority"),
                    (1, "Highest priority, and reserve"),
                    (2, "Highest priority, and wanted"),
                    (3, "Another position has this on reserve, with higher priority"),
                    (
                        4,
                        "Another position has this on reserve, with higher priority, but you have reserved",
                    ),
                    (
                        5,
                        "Another position has this on reserve, with higher priority, but you have them as wanted",
                    ),
                    (6, "Another position has this on reserve, with higher priority"),
                    (
                        7,
                        "Another position has this on wanted, with higher priority, but you have reserved",
                    ),
                    (
                        8,
                        "Another position has this on wanted, with higher priority, but you have them as wanted",
                    ),
                    (10, "Other position has priority"),
                ],
                default=0,
                help_text="The state of the applicant for the recruiter",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentadmission",
            name="recruiter_priority",
            field=models.IntegerField(
                choices=[
                    (0, "Not Set"),
                    (1, "Reserve"),
                    (2, "Wanted"),
                    (3, "Not Wanted"),
                ],
                default=0,
                help_text="The priority of the admission",
            ),
        ),
    ]
