# Generated by Django 5.2.15 on 2026-08-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0016_event_general_link_event_lastfm_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_nb',
        ),
    ]
