# Generated by Django 4.1.7 on 2023-04-06 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0016_remove_event_age_group_remove_event_status_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(choices=[('none', 'Ingen aldersgrense'), ('eighteen', '18 år'), ('twenty', '20 år'), ('mixed', '18 år (student), 20 år (ikke-student)')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='price_group',
            field=models.CharField(choices=[('included', 'Included with entrance'), ('free', 'Free'), ('billig', 'Paid'), ('registration', 'Free with registration'), ('custom', 'Custom')], default='free', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('archived', 'Arkivert'), ('cancelled', 'Avlyst'), ('deleted', 'Slettet')], default='active', max_length=30),
        ),
    ]
