# Generated by Django 5.2.15 on 2026-08-12 18:03

import django.db.models.deletion
import samfundet.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0016_event_general_link_event_lastfm_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('text_nb', models.CharField(max_length=128)),
                ('text_en', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=500, null=True, validators=[samfundet.validators.validate_site_banner_url])),
                ('new_tab', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site banner',
                'verbose_name_plural': 'Site banners',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='site_banner_end_after_start')],
            },
        ),
    ]
