# Generated by Django 5.2.15 on 2026-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0016_event_general_link_event_lastfm_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gangsection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sectionlogos/', verbose_name='Logo'),
        ),
    ]
