# Generated by Django 4.1.3 on 2022-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0016_table_venue_closing_friday_venue_closing_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='name_no',
        ),
        migrations.AddField(
            model_name='informationpage',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
