# Generated by Django 5.0.6 on 2024-05-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0017_recruitmentdatestat"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentCampusStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_stats",
                        to="samfundet.campus",
                    ),
                ),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
    ]
