# Generated by Django 5.2.17 on 2026-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_alter_gangsection_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='closedperiod',
            name='description_nb',
        ),
        migrations.AlterField(
            model_name='closedperiod',
            name='message_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Melding (engelsk)'),
        ),
        migrations.AlterField(
            model_name='closedperiod',
            name='message_nb',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Melding (norsk)'),
        ),
    ]
