# Generated by Django 5.2.15 on 2026-08-12 13:52

from datetime import time

from django.db import migrations, models


def preserve_closed_days(apps, schema_editor):
    Venue = apps.get_model('samfundet', 'Venue')
    for weekday in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'):
        Venue.objects.using(schema_editor.connection.alias).filter(
            **{
                f'opening_{weekday}': time(0, 0),
                f'closing_{weekday}': time(0, 0),
            }
        ).update(**{f'is_open_{weekday}': False})


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_alter_gangsection_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_open_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(preserve_closed_days, migrations.RunPython.noop),
    ]
