# Generated by Django 5.0.2 on 2024-06-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0017_recruitmentadmission_applicant_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentSeperatePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(help_text="Name of the position", max_length=100),
                ),
                (
                    "name_en",
                    models.CharField(help_text="Name of the position", max_length=100),
                ),
                (
                    "url",
                    models.URLField(help_text="URL to website of seperate recruitment"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recruitment that is recruiting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seperate_positions",
                        to="samfundet.recruitment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
