# Generated by Django 5.2.16 on 2026-09-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_alter_gangsection_logo'),
        ('samfundet', '0017_remove_closedperiod_description_en_and_more'),
    ]

    operations = [
    ]
