# Generated by Django 5.1.7 on 2025-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_recruitmentpositionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='applicant_state',
            field=models.IntegerField(choices=[(0, 'Unprocessed, action needed.'), (1, 'Applicants top priority, but set as reserve here.'), (2, 'Applicants top priority and wanted here.'), (3, 'Reserve for another position, unprocessed here. Action needed.'), (4, 'Reserve for another position and reserve here.'), (5, 'Reserve for another position, and wanted here.'), (6, 'Wanted for another position, and unprocessed here. Action needed.'), (7, 'Wanted for another position, and reserve here.'), (8, 'Wanted for another position and wanted here.'), (10, 'The applicant is not wanted for this position.')], default=0, help_text='The state of the applicant for the recruiter'),
        ),
    ]
