# Generated by Django 5.1.7 on 2025-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_recruitmentpositionstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='comment',
            field=models.TextField(blank=True, help_text='Application comment', null=True),
        ),
    ]
