# Generated by Django 5.1.7 on 2025-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_recruitmentpositionstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='open_for_other_positions',
            field=models.BooleanField(default=False, help_text='Is the applicant interested in any position they did not apply for?'),
        ),
    ]
