# Generated by Django 4.1.3 on 2022-11-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_remove_informationpage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='slug_field',
            field=models.SlugField(blank=True, help_text='Primary key, this field will identify the object and be used in the URL.', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst (engelsk)'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='text_no',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst (norsk)'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (engelsk)'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (norsk)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (engelsk)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tittel (norsk)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn (engelsk)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn (norsk)'),
        ),
    ]
