# Generated by Django 4.1.7 on 2023-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_alter_event_age_restriction_alter_event_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpricecustom',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='eventpricecustom',
            name='name_nb',
            field=models.CharField(default='test', max_length=140),
            preserve_default=False,
        ),
    ]
