# Generated by Django 5.1.1 on 2025-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_recruitmentpositionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
