# Generated by Django 5.1.5 on 2025-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0017_recruitmentpositionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
