# Generated by Django 5.2.17 on 2026-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_merge_20260902_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedperiod',
            name='message_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Melding (engelsk)'),
        ),
        migrations.AlterField(
            model_name='closedperiod',
            name='message_nb',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Melding (norsk)'),
        ),
    ]
