# Generated by Django 5.1.7 on 2025-03-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_recruitmentapplication_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.venue', to_field='slug', verbose_name='Lokale'),
        ),
    ]
