# Generated by Django 5.0.2 on 2024-06-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_recruitmentseperateposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentInterviewAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start_date', models.DateField(help_text='First possible date for interviews')),
                ('end_date', models.DateField(help_text='Last possible date for interviews')),
                ('start_time', models.TimeField(default='08:00:00', help_text='First possible time of day for interviews')),
                ('end_time', models.TimeField(default='23:00:00', help_text='Last possible time of day for interviews')),
                ('timeslot_interval', models.PositiveSmallIntegerField(default=30, help_text='The time interval (in minutes) between each timeslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='end_dt',
            field=models.DateTimeField(help_text='End of occupied time'),
        ),
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='recruitment',
            field=models.ForeignKey(help_text='Which recruitment this occupancy applies to', on_delete=django.db.models.deletion.CASCADE, to='samfundet.recruitment'),
        ),
        migrations.AlterField(
            model_name='occupiedtimeslot',
            name='start_dt',
            field=models.DateTimeField(help_text='Start of occupied time'),
        ),
        migrations.AddConstraint(
            model_name='occupiedtimeslot',
            constraint=models.UniqueConstraint(fields=('user', 'recruitment', 'start_dt', 'end_dt'), name='occupied_UNIQ'),
        ),
        migrations.AddField(
            model_name='recruitmentinterviewavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentinterviewavailability',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Which position this availability applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='samfundet.recruitmentposition'),
        ),
        migrations.AddField(
            model_name='recruitmentinterviewavailability',
            name='recruitment',
            field=models.ForeignKey(help_text='Which recruitment this availability applies to', on_delete=django.db.models.deletion.CASCADE, to='samfundet.recruitment'),
        ),
        migrations.AddField(
            model_name='recruitmentinterviewavailability',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
