# Generated by Django 4.1.3 on 2022-11-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_alter_informationpage_slug_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gang',
            old_name='group_type',
            new_name='gang_type',
        ),
    ]
