# Generated by Django 4.1.7 on 2023-04-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_rename_name_eventpricecustom_name_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPriceCustom',
            new_name='EventCustomTicket',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_group',
            new_name='ticket_type',
        ),
    ]
