# Generated by Django 5.0.2 on 2024-06-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0018_recruitmentseperateposition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruitmentposition",
            name="shared_interview_positions",
        ),
        migrations.CreateModel(
            name="RecruitmentPositionSharedInterviewGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recruitment that is recruiting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_groups",
                        to="samfundet.recruitment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="shared_interview_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared interviewgroup for position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="samfundet.recruitmentpositionsharedinterviewgroup",
            ),
        ),
    ]
