# Generated by Django 5.1.7 on 2025-04-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_recruitmentapplication_open_for_other_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='open_for_other_positions',
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='open_to_similar_positions',
            field=models.BooleanField(default=False, help_text='Is the applicant interested in any position they did not apply for, but which is similar to this?'),
        ),
    ]
