# Generated by Django 4.1.3 on 2022-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0019_rename_group_type_gang_gang_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn (norsk)')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn (engelsk)')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn (norsk)')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn (engelsk)')),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='description_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Beskrivelse (engelsk)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Beskrivelse (norsk)'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn (norsk)')),
                ('description_no', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (norsk)')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn (engelsk)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (engelsk)')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_member', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('food_preferences', models.ManyToManyField(blank=True, to='samfundet.foodpreference')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn (norsk)')),
                ('description_no', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (norsk)')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn (engelsk)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (engelsk)')),
                ('menu_items', models.ManyToManyField(blank=True, to='samfundet.menuitem')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
