# Generated by Django 5.0.2 on 2024-06-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0019_recruitmentinterviewavailability_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentCampusStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_stats",
                        to="samfundet.campus",
                    ),
                ),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentDateStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Time")),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentTimeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.PositiveIntegerField(verbose_name="Time")),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                (
                    "recruitment_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_stats",
                        to="samfundet.recruitmentstatistics",
                    ),
                ),
            ],
        ),
    ]
