# Generated by Django 5.2.17 on 2026-09-29 17:17

from django.db import migrations, models
from django.db.models import Q


def backfill_norwegian_from_english(apps, schema_editor):
    """
    title_nb and text_nb are about to become NOT NULL and required.
    Existing infoboxes may have them NULL or empty, so copy the English
    value into the Norwegian field for those rows. Without this, the
    AlterField below would fail on NULL rows, and empty rows would show
    as blank in the Norwegian UI.
    """
    Infobox = apps.get_model('samfundet', 'Infobox')
    Infobox.objects.filter(Q(title_nb__isnull=True) | Q(title_nb='')).update(title_nb=models.F('title_en'))
    Infobox.objects.filter(Q(text_nb__isnull=True) | Q(text_nb='')).update(text_nb=models.F('text_en'))


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0019_remove_closedperiod_description_en_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_norwegian_from_english, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='infobox',
            name='text_nb',
            field=models.CharField(max_length=255, verbose_name='Tekst (norsk)'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='title_nb',
            field=models.CharField(max_length=60, verbose_name='Tittel (norsk)'),
        ),
    ]
