# Generated by Django 4.1.7 on 2023-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0019_rename_eventpricecustom_eventcustomticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(choices=[('none', 'Ingen aldersgrense'), ('eighteen', '18 år'), ('twenty', '20 år'), ('mixed', '18 år (student), 20 år (ikke-student)')], default=None, max_length=30),
        ),
    ]
