# Generated by Django 5.2.17 on 2026-09-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0018_venue_is_open_friday_venue_is_open_monday_and_more'),
        ('samfundet', '0019_remove_closedperiod_description_en_and_more'),
    ]

    operations = [
    ]
