# Generated by Django 5.1.7 on 2025-03-30 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_recruitmentapplication_applicant_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publish_dt',
            new_name='end_dt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, choices=[('samfundet', 'Samfundet'), ('uka', 'UKA'), ('isfit', 'ISFiT'), ('external', 'Ekstern')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_from_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_to_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('public', 'Offentlig'), ('private', 'Privat'), ('archived', 'Arkivert'), ('cancelled', 'Avlyst'), ('deleted', 'Slettet')], default='public', max_length=30),
        ),
    ]
