# Generated by Django 4.1.7 on 2023-04-07 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_event_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_tickets',
            field=models.ManyToManyField(blank=True, to='samfundet.eventcustomticket'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_emails',
            field=models.ManyToManyField(blank=True, to='samfundet.nonmemberemailregistration'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
