# Generated by Django 4.1.3 on 2022-11-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_foodcategory_foodpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.foodcategory'),
        ),
    ]
