# Generated by Django 5.1.7 on 2025-04-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_recruitmentapplication_applicant_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
