# Generated by Django 5.1.7 on 2025-04-24 17:47

import django.db.models.deletion
import samfundet.models.utils.string_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_recruitmentapplication_applicant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruitment',
            field=models.ForeignKey(help_text='The recruitment that is recruiting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='samfundet.recruitment'),
        ),
        migrations.CreateModel(
            name='ApplicationFileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('application_file', models.FileField(upload_to=samfundet.models.utils.string_utils.upload_to_application_filepath)),
                ('application_file_type', models.CharField(blank=True, max_length=50)),
                ('application', models.ForeignKey(help_text='The recruitment application this file is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='samfundet.recruitmentapplication')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
