# Generated by Django 5.1.7 on 2025-03-29 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_recruitmentapplication_applicant_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publish_dt',
            new_name='end_dt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_from_dt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 16, 25, 21, 460974, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_to_dt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 16, 25, 44, 947459, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('public', 'Offentlig'), ('private', 'Privat'), ('archived', 'Arkivert'), ('cancelled', 'Avlyst'), ('deleted', 'Slettet')], default='public', max_length=30),
        ),
    ]
