# Generated by Django 5.1.7 on 2025-04-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0020_alter_recruitmentapplication_applicant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='open_to_similar_positions',
            field=models.BooleanField(default=False, help_text='Is the applicant interested in any position they did not apply for, but which is similar to this?'),
        ),
    ]
