# Generated by Django 5.1.7 on 2025-03-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0021_rename_publish_dt_event_end_dt_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_external_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
