# Generated by Django 4.1.3 on 2022-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0021_saksdokument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saksdokument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/saksdokument/'),
        ),
        migrations.AlterField(
            model_name='saksdokument',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saksdokument',
            name='title_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tittel (Engelsk)'),
        ),
        migrations.AlterField(
            model_name='saksdokument',
            name='title_no',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tittel (Norsk)'),
        ),
    ]
