# Generated by Django 4.1.7 on 2023-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0021_alter_event_custom_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billig_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
