# Generated by Django 5.1.7 on 2025-03-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0022_event_email_contact_event_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, choices=[('samfundet', 'Samfundet'), ('uka', 'UKA'), ('isfit', 'ISFiT')], max_length=30, null=True),
        ),
    ]
