# Generated by Django 4.1.3 on 2022-12-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0022_table_venue_alter_table_name_en_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='when',
        ),
    ]
