# Generated by Django 4.1.7 on 2023-04-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0022_event_billig_id'),
        ('samfundet', '0022_userpreference_cursor_trail'),
    ]

    operations = [
    ]
