# Generated by Django 5.1.7 on 2025-04-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0022_alter_event_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
