# Generated by Django 5.1.9 on 2025-08-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0023_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
