# Generated by Django 4.1.7 on 2023-04-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0023_merge_20230408_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilligEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('sale_from', models.DateTimeField()),
                ('sale_to', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'BilligEvent',
                'verbose_name_plural': 'BilligEvents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligPriceGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_group_id', models.IntegerField()),
                ('name', models.CharField(max_length=140)),
                ('can_be_put_on_card', models.BooleanField()),
                ('membership_needed', models.BooleanField()),
                ('netsale', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BilligPriceGroup',
                'verbose_name_plural': 'BilligPriceGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligTicketGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(max_length=140)),
                ('num', models.PositiveIntegerField()),
                ('num_sold', models.PositiveIntegerField()),
                ('ticket_limit', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'BilligTicketGroup',
                'verbose_name_plural': 'BilligTicketGroups',
                'managed': False,
            },
        ),
    ]
