# Generated by Django 4.1.3 on 2022-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0023_remove_booking_duration_remove_booking_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_nr',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
