# Generated by Django 5.1.9 on 2025-08-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0023_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.venue', verbose_name='Lokale'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, default='storsalen', help_text='Primary key, this field will identify the object and be used in the URL.', max_length=64, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
