# Generated by Django 4.1.7 on 2023-04-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0023_merge_20230408_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilligEvent',
            fields=[
                ('id', models.IntegerField(db_column='event', primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=140)),
                ('sale_from', models.DateTimeField()),
                ('sale_to', models.DateTimeField()),
                ('hidden', models.BooleanField()),
            ],
            options={
                'verbose_name': 'BilligEvent',
                'verbose_name_plural': 'BilligEvents',
                'db_table': 'billig.event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligPriceGroup',
            fields=[
                ('id', models.IntegerField(db_column='price_group', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='price_group_name', max_length=140)),
                ('can_be_put_on_card', models.BooleanField()),
                ('membership_needed', models.BooleanField()),
                ('netsale', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BilligPriceGroup',
                'verbose_name_plural': 'BilligPriceGroups',
                'db_table': 'billig.price_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilligTicketGroup',
            fields=[
                ('id', models.IntegerField(db_column='ticket_group', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ticket_group_name', max_length=140)),
                ('num', models.PositiveIntegerField()),
                ('num_sold', models.PositiveIntegerField()),
                ('ticket_limit', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'BilligTicketGroup',
                'verbose_name_plural': 'BilligTicketGroups',
                'db_table': 'billig.ticket_group',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='billig_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
