# Generated by Django 4.1.7 on 2023-04-09 09:19

from django.db import migrations, models
import samfundet.models.billig


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0024_billigevent_billigpricegroup_billigticketgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='billig_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=samfundet.models.billig.BilligEvent),
        ),
    ]
