# Generated by Django 4.1.3 on 2022-12-04 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0024_booking_email_booking_first_name_booking_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gang',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='gangtype',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='gang',
            name='info_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samfundet.informationpage', verbose_name='Infoside'),
        ),
        migrations.AddField(
            model_name='gang',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ganglogos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='gang',
            name='name_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn'),
        ),
        migrations.AddField(
            model_name='gangtype',
            name='title_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Gruppetype'),
        ),
    ]
