# Generated by Django 4.1.3 on 2022-12-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0024_booking_email_booking_first_name_booking_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saksdokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tittel (Norsk)')),
                ('title_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tittel (Engelsk)')),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FS_REFERAT', 'FS-Referat'), ('STYRET', 'Styret'), ('RADET', 'Rådet'), ('ARSBERETNINGER', 'Årsberetninger, regnskap og budsjettkunngjøringer')], default='FS_REFERAT', max_length=25)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/saksdokument/')),
            ],
            options={
                'verbose_name': 'Saksdokument',
                'verbose_name_plural': 'Saksdokument',
            },
        ),
    ]
