# Generated by Django 4.1.6 on 2023-04-18 19:59

import django.contrib.auth.validators
from django.db import migrations
import samfundet.models.general

def lowercase_usernames(apps, schema_editor):
    User = apps.get_model('samfundet', 'User')
    for user in User.objects.all():
        if user.username != user.username.lower():
            user.username = user.username.lower()
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0024_billigevent_billigpricegroup_billigticketgroup_and_more'),
    ]

    operations = [
        migrations.RunPython(lowercase_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=samfundet.models.general.UsernameField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
