# Generated by Django 4.1.7 on 2023-04-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0026_alter_event_billig_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billigevent',
            table='billig.event',
        ),
        migrations.AlterModelTable(
            name='billigpricegroup',
            table='billig.price_group',
        ),
        migrations.AlterModelTable(
            name='billigticketgroup',
            table='billig.ticket_group',
        ),
    ]
