# Generated by Django 4.1.3 on 2022-12-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0026_remove_gang_name_remove_gangtype_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Forkortelse'),
        ),
        migrations.AlterField(
            model_name='gang',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn Engelsk'),
        ),
        migrations.AlterField(
            model_name='gang',
            name='name_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Navn Norsk'),
        ),
        migrations.AlterField(
            model_name='gangtype',
            name='title_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Gruppetype Engelsk'),
        ),
        migrations.AlterField(
            model_name='gangtype',
            name='title_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Gruppetype Norsk'),
        ),
    ]
