# Generated by Django 4.2 on 2023-04-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0026_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_nb', models.CharField(max_length=60, verbose_name='Infoboks titel (norsk)')),
                ('text_nb', models.CharField(max_length=255, verbose_name='Infoboks tekst (norsk)')),
                ('title_en', models.CharField(max_length=60, verbose_name='Infoboks tekst (engelsk)')),
                ('text_en', models.CharField(max_length=255, verbose_name='Infoboks tekst (engelsk)')),
                ('color', models.CharField(max_length=15, verbose_name='Infoboks hexcolor eller css color-constant')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Infoboks utgående link')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samfundet.image', verbose_name='Infoboks bilde')),
            ],
            options={
                'verbose_name': 'Infoboks',
                'verbose_name_plural': 'Infobokser',
            },
        ),
    ]
