# Generated by Django 4.2.1 on 2023-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0027_infobox'),
    ]

    operations = [
        migrations.AddField(
            model_name='gang',
            name='event_admin',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='gang_as_event_admin',
                to='auth.group',
                verbose_name='Arrangementgruppe'
            ),
        ),
        migrations.AddField(
            model_name='gang',
            name='gang_leader',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_as_leader', to='auth.group', verbose_name='Gangleder'
            ),
        ),
        migrations.AddField(
            model_name='gang',
            name='recruitment_admin',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='gang_as_recruitment_admin',
                to='auth.group',
                verbose_name='Innganggruppe'
            ),
        ),
        migrations.AlterField(
            model_name='gang',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Forkortelse'),
        ),
    ]
