# Generated by Django 4.1.7 on 2023-04-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0027_alter_billigevent_table_alter_billigpricegroup_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='billig_id',
        ),
        migrations.AddField(
            model_name='event',
            name='billig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billig_event', to='samfundet.billigevent'),
        ),
    ]
