# Generated by Django 4.1.7 on 2023-04-09 18:59

from django.db import migrations, models
import samfundet.models.billig


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0028_remove_event_billig_id_event_billig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='billig',
        ),
        migrations.AddField(
            model_name='event',
            name='billig_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=samfundet.models.billig.BilligEvent),
        ),
    ]
