# Generated by Django 4.1.3 on 2022-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0029_alter_informationpage_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn Engelsk'),
        ),
        migrations.AlterField(
            model_name='gang',
            name='name_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Navn Norsk'),
        ),
    ]
