# Generated by Django 4.2.1 on 2023-06-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0029_gang_event_admin_gang_gang_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nb', models.CharField(help_text='Name of the recruitment', max_length=100)),
                ('name_en', models.CharField(help_text='Name of the recruitment', max_length=100)),
                ('visible_from', models.DateTimeField(help_text='When it becomes visible for applicants')),
                ('actual_application_deadline', models.DateTimeField(help_text='Last point an application can be sent, typically a bit after the shown deadline to avoid getting a lot of extra mail')),
                ('shown_application_deadline', models.DateTimeField(help_text='The deadline that is shown to applicants')),
                ('reprioritization_deadline_for_applicant', models.DateTimeField(help_text='Before allocation meeting')),
                ('reprioritization_deadline_for_groups', models.DateTimeField(help_text='Reprioritization deadline for groups')),
                ('organization', models.CharField(choices=[('samfundet', 'Samfundet'), ('isfit', 'ISFiT'), ('uka', 'UKA')], help_text='Organization', max_length=10)),
            ],
            options={
                'unique_together': {('organization',)},
            },
        ),
    ]
