# Generated by Django 4.2.1 on 2023-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0029_gang_event_admin_gang_gang_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='slug_field',
            field=models.SlugField(blank=True, help_text='Primary key, this field will identify the object and be used in the URL.', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
