# Generated by Django 4.2.1 on 2023-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0029_gang_event_admin_gang_gang_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editors',
            field=models.ManyToManyField(blank=True, to='samfundet.gang'),
        ),
    ]
