# Generated by Django 4.2.1 on 2023-06-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0030_alter_informationpage_slug_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nb', models.CharField(help_text='Name of the recruitment', max_length=100)),
                ('name_en', models.CharField(help_text='Name of the recruitment', max_length=100)),
                ('visible_from', models.DateTimeField(help_text='When it becomes visible for applicants')),
                ('actual_application_deadline', models.DateTimeField(help_text='Last point an application can be sent, typically a bit after the shown deadline to avoid getting a lot of extra mail')),
                ('shown_application_deadline', models.DateTimeField(help_text='The deadline that is shown to applicants')),
                ('reprioritization_deadline_for_applicant', models.DateTimeField(help_text='Before allocation meeting')),
                ('reprioritization_deadline_for_groups', models.DateTimeField(help_text='Reprioritization deadline for groups')),
                ('organization', models.ForeignKey(help_text='The organization that is recruiting', on_delete=django.db.models.deletion.CASCADE, to='samfundet.organization')),
            ],
        ),
        migrations.AddField(
            model_name='gang',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gangs', to='samfundet.organization', verbose_name='Organisasjon'),
        ),
    ]
