# Generated by Django 4.1.3 on 2022-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0030_alter_gang_name_en_alter_gang_name_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(default='hello', max_length=140),
            preserve_default=False,
        ),
    ]
