# Generated by Django 4.2.1 on 2023-06-06 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0031_recruitmentposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentposition',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for the position', null=True, related_name='intervjues', to=settings.AUTH_USER_MODEL),
        ),
    ]
