# Generated by Django 4.1.3 on 2022-12-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0031_eventgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_dt',
        ),
        migrations.AddField(
            model_name='event',
            name='age_group',
            field=models.CharField(blank=True, choices=[('None', 'Ingen aldersgrense'), ('EIGHTEEN', '18 år'), ('TWENTY', '20 år'), ('MIXED', '18 år (student), 20 år (ikke-student)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='codeword',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status_group',
            field=models.CharField(blank=True, choices=[('active', 'Aktiv'), ('archived', 'Arkivert'), ('canceled', 'Avlyst')], max_length=30, null=True),
        ),
    ]
