# Generated by Django 4.2.1 on 2023-06-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('samfundet', '0032_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gang',
            name='event_admin',
        ),
        migrations.RemoveField(
            model_name='gang',
            name='gang_leader',
        ),
        migrations.RemoveField(
            model_name='gang',
            name='recruitment_admin',
        ),
        migrations.AddField(
            model_name='event',
            name='editors',
            field=models.ManyToManyField(blank=True, to='samfundet.gang'),
        ),
        migrations.AddField(
            model_name='gang',
            name='event_admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_as_event_admin_group', to='auth.group', verbose_name='Arrangementgruppe'),
        ),
        migrations.AddField(
            model_name='gang',
            name='gang_leader_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_as_leader', to='auth.group', verbose_name='Gangleder'),
        ),
        migrations.AddField(
            model_name='gang',
            name='recruitment_admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_as_recruitment_admin_group', to='auth.group', verbose_name='Innganggruppe'),
        ),
    ]
