# Generated by Django 4.2.1 on 2023-06-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0032_recruitmentposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gangs', to='samfundet.organization', unique=True, verbose_name='Organisasjon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
