# Generated by Django 4.1.4 on 2023-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0032_remove_event_end_dt_event_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_no', models.TextField(blank=True, null=True, verbose_name='Melding (norsk)')),
                ('description_no', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (norsk)')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Melding (engelsk)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beskrivelse (engelsk)')),
                ('start_dt', models.DateField(blank=True, verbose_name='Start dato')),
                ('end_dt', models.DateField(blank=True, verbose_name='Slutt dato')),
            ],
            options={
                'verbose_name': 'Stengt periode',
                'verbose_name_plural': 'Stengt perioder',
            },
        ),
    ]
