# Generated by Django 4.1.4 on 2023-01-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0033_closedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('tags', models.ManyToManyField(blank=True, related_name='images', to='samfundet.tag')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
