# Generated by Django 4.2.1 on 2023-06-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0033_alter_gang_organization_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gangs', to='samfundet.organization', verbose_name='Organisasjon'),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for the position', related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
