# Generated by Django 4.1.4 on 2023-01-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0033_closedperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedperiod',
            old_name='description_no',
            new_name='description_nb',
        ),
        migrations.RenameField(
            model_name='closedperiod',
            old_name='message_no',
            new_name='message_nb',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_long_no',
            new_name='description_long_nb',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_short_no',
            new_name='description_short_nb',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_no',
            new_name='title_nb',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='name_no',
            new_name='name_nb',
        ),
        migrations.RenameField(
            model_name='foodpreference',
            old_name='name_no',
            new_name='name_nb',
        ),
        migrations.RenameField(
            model_name='gang',
            old_name='name_no',
            new_name='name_nb',
        ),
        migrations.RenameField(
            model_name='gangtype',
            old_name='title_no',
            new_name='title_nb',
        ),
        migrations.RenameField(
            model_name='informationpage',
            old_name='text_no',
            new_name='text_nb',
        ),
        migrations.RenameField(
            model_name='informationpage',
            old_name='title_no',
            new_name='title_nb',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='description_no',
            new_name='description_nb',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name_no',
            new_name='name_nb',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='description_no',
            new_name='description_nb',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name_no',
            new_name='name_nb',
        ),
        migrations.RenameField(
            model_name='saksdokument',
            old_name='title_no',
            new_name='title_nb',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='description_no',
            new_name='description_nb',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name_no',
            new_name='name_nb',
        ),
    ]
