# Generated by Django 4.2.1 on 2023-06-12 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0034_alter_organization_name_recruitmentposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_text', models.TextField(help_text='Admission text for the admission')),
                ('applicant_priority', models.IntegerField(help_text='The priority of the admission')),
                ('interview_time', models.DateTimeField(blank=True, help_text='The time of the interview', null=True)),
                ('interview_location', models.CharField(blank=True, help_text='The location of the interview', max_length=100, null=True)),
                ('recruiter_priority', models.IntegerField(choices=[(0, 'Not Set'), (1, 'Not Wanted'), (2, 'Wanted'), (3, 'Reserve')], default=0, help_text='The priority of the admission')),
                ('recruiter_status', models.IntegerField(choices=[(0, 'Nothing'), (1, 'Called and Accepted'), (2, 'Called and Rejected'), (3, 'Automatic Rejection')], default=0, help_text='The status of the admission')),
                ('recruitment', models.ForeignKey(help_text='The recruitment that is recruiting', on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='samfundet.recruitment')),
                ('recruitment_position', models.ForeignKey(help_text='The recruitment position that is recruiting', on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='samfundet.recruitmentposition')),
                ('user', models.ForeignKey(help_text='The user that is applying', on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
