# Generated by Django 4.2.3 on 2023-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0035_recruitmentadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
