# Generated by Django 4.2.3 on 2023-09-14 16:35

from django.db import migrations, models
import samfundet.models.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0036_venue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=samfundet.models.utils.fields.PhoneNumberField(default=59696969, max_length=15, verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
