# Generated by Django 4.2.3 on 2023-09-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0036_venue_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('debug', 'Can view debug mode'), ('impersonate', 'Can impersonate users')]},
        ),
    ]
