# Generated by Django 4.2.3 on 2023-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0037_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentadmission',
            name='interview_location',
            field=models.CharField(blank=True, help_text='Where the intevjuee should wait', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InterviewRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room', max_length=255)),
                ('location', models.CharField(help_text='Physical location, eg. campus', max_length=255)),
                ('start_time', models.DateTimeField(help_text='Start time of availability')),
                ('end_time', models.DateTimeField(help_text='End time of availability')),
                ('gang', models.ForeignKey(blank=True, help_text='The gang that booked the room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='samfundet.gang')),
                ('recruitment', models.ForeignKey(help_text='The recruitment that is recruiting', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='samfundet.recruitment')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentadmission',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room where the interview is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='samfundet.interviewroom'),
        ),
    ]
