# Generated by Django 4.2.3 on 2023-10-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0038_alter_recruitmentadmission_interview_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='interview_time',
        ),
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='room',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_time', models.DateTimeField(help_text='The time of the interview')),
                ('notes', models.TextField(help_text='Notes for the interview')),
                ('admissions', models.ForeignKey(help_text='The admission that is being interviewed', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='samfundet.recruitmentadmission')),
                ('room', models.ForeignKey(blank=True, help_text='Room where the interview is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='samfundet.interviewroom')),
            ],
        ),
    ]
