# Generated by Django 4.2.3 on 2023-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0038_alter_recruitmentadmission_interview_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Notes for the interview')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the notes')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentadmission',
            name='interview_notes',
            field=models.ManyToManyField(blank=True, help_text='Notes for the interview', to='samfundet.interviewnotes'),
        ),
    ]
