# Generated by Django 4.2.3 on 2023-10-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0038_alter_recruitmentadmission_interview_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='interview_time',
        ),
        migrations.RemoveField(
            model_name='recruitmentadmission',
            name='room',
        ),
        migrations.AddField(
            model_name='recruitmentposition',
            name='shared_interview_positions',
            field=models.ManyToManyField(blank=True, help_text='Positions with shared interview', to='samfundet.recruitmentposition'),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Interviewers for the position', related_name='interviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_time', models.DateTimeField(blank=True, help_text='The time of the interview', null=True)),
                ('interview_location', models.CharField(blank=True, help_text='The location of the interview', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes for the interview', null=True)),
                ('room', models.ForeignKey(blank=True, help_text='Room where the interview is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='samfundet.interviewroom')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentadmission',
            name='interview',
            field=models.ForeignKey(blank=True, help_text='The interview for the admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='samfundet.interview'),
        ),
    ]
