# Generated by Django 4.2.3 on 2023-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0038_alter_recruitmentadmission_interview_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recommendations_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='recommendations_nb',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
