# Generated by Django 4.2.5 on 2023-09-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0039_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentapplicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
    ]
