# Generated by Django 4.2.6 on 2023-11-16 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0040_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentadmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recruitmentadmission',
            name='recruiter_status',
            field=models.IntegerField(choices=[(0, 'Not Set'), (1, 'Called and Accepted'), (2, 'Called and Rejected'), (3, 'Automatic Rejection')], default=0, help_text='The status of the admission'),
        ),
    ]
