# Generated by Django 4.2.6 on 2023-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0040_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentadmission',
            name='recruiter_priority',
            field=models.IntegerField(choices=[(0, 'Not Set'), (1, 'Not Wanted'), (2, 'Wanted'), (3, 'Reserve')], default=1, help_text='The priority of the admission'),
        ),
    ]
