# Generated by Django 4.2.6 on 2023-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0040_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentposition',
            name='norwegian_applicants_only',
            field=models.BooleanField(default=False, help_text='Is this position only for Norwegian applicants?'),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='default_admission_letter_en',
            field=models.TextField(blank=True, help_text='Default admission letter for the position', null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='long_description_en',
            field=models.TextField(blank=True, help_text='Long description of the position', null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentposition',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Short description of the position', max_length=100, null=True),
        ),
    ]
