# Generated by Django 4.2.6 on 2023-11-15 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('samfundet', '0041_alter_recruitmentadmission_recruiter_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentadmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
