# Generated by Django 5.0 on 2023-12-17 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0041_recruitmentposition_norwegian_applicants_only_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occupiedtimeslot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_dt",
                    models.DateTimeField(help_text="The time of the interview"),
                ),
                ("end_dt", models.DateTimeField(help_text="The time of the interview")),
                (
                    "recruitment",
                    models.ForeignKey(
                        help_text="Occupied timeslots for the users for this recruitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samfundet.recruitment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Occupied timeslots for user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupied_timeslots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
