# Generated by Django 5.0 on 2023-12-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samfundet", "0042_occupiedtimeslot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_dt",
            field=models.DateTimeField(
                default="2018-06-12 09:55:22", verbose_name="Sluttid"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_dt",
            field=models.DateTimeField(
                default="2018-06-12 09:55:22", verbose_name="Starttid"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="samfundet.table",
                verbose_name="Bord",
            ),
        ),
    ]
