const fs = require('fs');
const path = require('path');
const routes = require('../src/routes/frontend.ts');

function main() {
  const ROUTES_FRONTEND = routes.ROUTES_FRONTEND;
  let buffer = `"""
THIS FILE IS AUTOGENERATED!
DO NOT WRITE IN THIS FILE, AS IT WILL BE OVERWRITTEN ON NEXT UPDATE.

Frontend routes meant for consumption by the Django backend.

Run 'yarn export-routes' in the frontend directory to regenerate
"""

`;

  for (const [name, reactPath] of Object.entries(ROUTES_FRONTEND)) {
    const varName = name.toUpperCase();
    const djangoPath = (reactPath as string).replace(/:(\w+)/g, '<$1>'); // e.g. /events/:id/ -> /events/<id>/
    buffer += `${varName} = "${djangoPath}"\n`;
  }

  const outputPath = path.join(__dirname, '../../backend/samfundet/routing/frontend_routes.py');
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, buffer);

  console.log(`Generated Python routes file with ${Object.keys(ROUTES_FRONTEND).length} routes to ${outputPath}`);
}

try {
  main();
} catch (error) {
  console.error('Failed to generate Python routes file:\n', error);
  process.exit(1);
}
