import { PERM } from '~/permissions';
import { ROUTES } from '~/routes';
import type { AdminAppletCategory } from '~/types.ts';

export const appletCategories: AdminAppletCategory[] = [
  {
    title_en: 'General',
    title_nb: 'Generelt',
    applets: [
      {
        title_nb: 'Arrangementer',
        title_en: 'Events',
        perm: PERM.SAMFUNDET_ADD_EVENT,
        icon: 'material-symbols:calendar-month-outline-rounded',
        url: ROUTES.frontend.admin_events,
        feature: 'events',
      },
      {
        title_nb: 'Informasjonssider',
        title_en: 'Information pages',
        perm: PERM.SAMFUNDET_ADD_INFORMATIONPAGE,
        icon: 'ph:note-pencil-light',
        url: ROUTES.frontend.admin_information,
        feature:'information',
      },
      {
        title_nb: 'Åpningstider',
        title_en: 'Opening hours',
        perm: PERM.SAMFUNDET_CHANGE_VENUE,
        icon: 'mdi:clock-time-eight-outline',
        url: ROUTES.frontend.admin_opening_hours,
        feature: 'openingHours',
      },
      {
        title_nb: 'Stengte perioder',
        title_en: 'Closed periods',
        perm: PERM.SAMFUNDET_ADD_CLOSEDPERIOD,
        icon: 'solar:moon-sleep-bold',
        url: ROUTES.frontend.admin_closed,
        feature: 'openingHours',
      },
      {
        title_nb: 'Bildearkiv',
        title_en: 'Images',
        perm: PERM.SAMFUNDET_ADD_IMAGE,
        icon: 'clarity:image-gallery-line',
        url: ROUTES.frontend.admin_images,
        feature: 'images',
      },
      {
        title_nb: 'Saksdokumenter',
        title_en: 'Documents',
        perm: PERM.SAMFUNDET_ADD_SAKSDOKUMENT,
        icon: 'mdi:file-document-outline',
        url: ROUTES.frontend.admin_saksdokumenter,
        feature: 'documents',
      },
      {
        title_nb: 'Brukere',
        title_en: 'Users',
        perm: PERM.SAMFUNDET_VIEW_USER,
        icon: 'mdi:person-search',
        url: ROUTES.frontend.admin_users,
        feature: 'users',
      },
      {
        title_nb: 'Roller',
        title_en: 'Roles',
        perm: PERM.SAMFUNDET_VIEW_ROLE,
        icon: 'ph:user-circle-gear',
        url: ROUTES.frontend.admin_roles,
        feature: 'roles',
      },
      {
        title_nb: 'Gjenger',
        title_en: 'Gangs',
        perm: PERM.SAMFUNDET_ADD_GANG,
        icon: 'mdi:people-group',
        url: ROUTES.frontend.admin_gangs,
        feature: 'gangs',
      },
      {
        title_nb: 'Opptak',
        title_en: 'Recruitment',
        perm: PERM.SAMFUNDET_ADD_RECRUITMENT,
        icon: 'mdi:briefcase-search',
        url: ROUTES.frontend.admin_recruitment,
        feature: 'recruitment',
      },
      {
        title_nb: 'Lyche Reservasjon',
        title_en: 'Lyche Reservation',
        perm: PERM.SAMFUNDET_VIEW_RESERVATION,
        icon: 'mdi:food-outline',
        url: ROUTES.frontend.admin_sulten_reservations,
        feature: 'sulten',
      },
      {
        title_nb: 'Lyche Meny',
        title_en: 'Lyche Menu',
        perm: PERM.SAMFUNDET_VIEW_MENU,
        icon: 'bx:food-menu',
        url: ROUTES.frontend.admin_sulten_menu,
        feature: 'sulten',
      },
    ],
  },
];
