# yapf: disable
"""
THIS FILE IS AUTOGENERATED.
DO NOT WRITE IN THIS FILE, AS IT WILL BE OVERWRITTEN ON NEXT UPDATE.

THIS FILE WAS GENERATED BY: root.management.commands.generate_permissions
LAST UPDATE: 2023-03-25 22:39:42.093381+00:00
"""

############################################################

### admin ###
ADMIN_ADD_LOGENTRY = 'admin.add_logentry'
ADMIN_CHANGE_LOGENTRY = 'admin.change_logentry'
ADMIN_DELETE_LOGENTRY = 'admin.delete_logentry'
ADMIN_VIEW_LOGENTRY = 'admin.view_logentry'
### End: admin ###

### auth ###
AUTH_ADD_GROUP = 'auth.add_group'
AUTH_CHANGE_GROUP = 'auth.change_group'
AUTH_DELETE_GROUP = 'auth.delete_group'
AUTH_VIEW_GROUP = 'auth.view_group'

AUTH_ADD_PERMISSION = 'auth.add_permission'
AUTH_CHANGE_PERMISSION = 'auth.change_permission'
AUTH_DELETE_PERMISSION = 'auth.delete_permission'
AUTH_VIEW_PERMISSION = 'auth.view_permission'
### End: auth ###

### contenttypes ###
CONTENTTYPES_ADD_CONTENTTYPE = 'contenttypes.add_contenttype'
CONTENTTYPES_CHANGE_CONTENTTYPE = 'contenttypes.change_contenttype'
CONTENTTYPES_DELETE_CONTENTTYPE = 'contenttypes.delete_contenttype'
CONTENTTYPES_VIEW_CONTENTTYPE = 'contenttypes.view_contenttype'
### End: contenttypes ###

### guardian ###
GUARDIAN_ADD_GROUPOBJECTPERMISSION = 'guardian.add_groupobjectpermission'
GUARDIAN_CHANGE_GROUPOBJECTPERMISSION = 'guardian.change_groupobjectpermission'
GUARDIAN_DELETE_GROUPOBJECTPERMISSION = 'guardian.delete_groupobjectpermission'
GUARDIAN_VIEW_GROUPOBJECTPERMISSION = 'guardian.view_groupobjectpermission'

GUARDIAN_ADD_USEROBJECTPERMISSION = 'guardian.add_userobjectpermission'
GUARDIAN_CHANGE_USEROBJECTPERMISSION = 'guardian.change_userobjectpermission'
GUARDIAN_DELETE_USEROBJECTPERMISSION = 'guardian.delete_userobjectpermission'
GUARDIAN_VIEW_USEROBJECTPERMISSION = 'guardian.view_userobjectpermission'
### End: guardian ###

### samfundet ###
SAMFUNDET_ADD_BOOKING = 'samfundet.add_booking'
SAMFUNDET_CHANGE_BOOKING = 'samfundet.change_booking'
SAMFUNDET_DELETE_BOOKING = 'samfundet.delete_booking'
SAMFUNDET_VIEW_BOOKING = 'samfundet.view_booking'

SAMFUNDET_ADD_CLOSEDPERIOD = 'samfundet.add_closedperiod'
SAMFUNDET_CHANGE_CLOSEDPERIOD = 'samfundet.change_closedperiod'
SAMFUNDET_DELETE_CLOSEDPERIOD = 'samfundet.delete_closedperiod'
SAMFUNDET_VIEW_CLOSEDPERIOD = 'samfundet.view_closedperiod'

SAMFUNDET_ADD_EVENT = 'samfundet.add_event'
SAMFUNDET_CHANGE_EVENT = 'samfundet.change_event'
SAMFUNDET_DELETE_EVENT = 'samfundet.delete_event'
SAMFUNDET_VIEW_EVENT = 'samfundet.view_event'

SAMFUNDET_ADD_EVENTGROUP = 'samfundet.add_eventgroup'
SAMFUNDET_CHANGE_EVENTGROUP = 'samfundet.change_eventgroup'
SAMFUNDET_DELETE_EVENTGROUP = 'samfundet.delete_eventgroup'
SAMFUNDET_VIEW_EVENTGROUP = 'samfundet.view_eventgroup'

SAMFUNDET_ADD_FOODCATEGORY = 'samfundet.add_foodcategory'
SAMFUNDET_CHANGE_FOODCATEGORY = 'samfundet.change_foodcategory'
SAMFUNDET_DELETE_FOODCATEGORY = 'samfundet.delete_foodcategory'
SAMFUNDET_VIEW_FOODCATEGORY = 'samfundet.view_foodcategory'

SAMFUNDET_ADD_FOODPREFERENCE = 'samfundet.add_foodpreference'
SAMFUNDET_CHANGE_FOODPREFERENCE = 'samfundet.change_foodpreference'
SAMFUNDET_DELETE_FOODPREFERENCE = 'samfundet.delete_foodpreference'
SAMFUNDET_VIEW_FOODPREFERENCE = 'samfundet.view_foodpreference'

SAMFUNDET_ADD_GANG = 'samfundet.add_gang'
SAMFUNDET_CHANGE_GANG = 'samfundet.change_gang'
SAMFUNDET_DELETE_GANG = 'samfundet.delete_gang'
SAMFUNDET_VIEW_GANG = 'samfundet.view_gang'

SAMFUNDET_ADD_GANGTYPE = 'samfundet.add_gangtype'
SAMFUNDET_CHANGE_GANGTYPE = 'samfundet.change_gangtype'
SAMFUNDET_DELETE_GANGTYPE = 'samfundet.delete_gangtype'
SAMFUNDET_VIEW_GANGTYPE = 'samfundet.view_gangtype'

SAMFUNDET_ADD_IMAGE = 'samfundet.add_image'
SAMFUNDET_CHANGE_IMAGE = 'samfundet.change_image'
SAMFUNDET_DELETE_IMAGE = 'samfundet.delete_image'
SAMFUNDET_VIEW_IMAGE = 'samfundet.view_image'

SAMFUNDET_ADD_INFORMATIONPAGE = 'samfundet.add_informationpage'
SAMFUNDET_CHANGE_INFORMATIONPAGE = 'samfundet.change_informationpage'
SAMFUNDET_DELETE_INFORMATIONPAGE = 'samfundet.delete_informationpage'
SAMFUNDET_VIEW_INFORMATIONPAGE = 'samfundet.view_informationpage'

SAMFUNDET_ADD_MENU = 'samfundet.add_menu'
SAMFUNDET_CHANGE_MENU = 'samfundet.change_menu'
SAMFUNDET_DELETE_MENU = 'samfundet.delete_menu'
SAMFUNDET_VIEW_MENU = 'samfundet.view_menu'

SAMFUNDET_ADD_MENUITEM = 'samfundet.add_menuitem'
SAMFUNDET_CHANGE_MENUITEM = 'samfundet.change_menuitem'
SAMFUNDET_DELETE_MENUITEM = 'samfundet.delete_menuitem'
SAMFUNDET_VIEW_MENUITEM = 'samfundet.view_menuitem'

SAMFUNDET_ADD_PROFILE = 'samfundet.add_profile'
SAMFUNDET_CHANGE_PROFILE = 'samfundet.change_profile'
SAMFUNDET_DELETE_PROFILE = 'samfundet.delete_profile'
SAMFUNDET_VIEW_PROFILE = 'samfundet.view_profile'

SAMFUNDET_ADD_SAKSDOKUMENT = 'samfundet.add_saksdokument'
SAMFUNDET_CHANGE_SAKSDOKUMENT = 'samfundet.change_saksdokument'
SAMFUNDET_DELETE_SAKSDOKUMENT = 'samfundet.delete_saksdokument'
SAMFUNDET_VIEW_SAKSDOKUMENT = 'samfundet.view_saksdokument'

SAMFUNDET_ADD_TABLE = 'samfundet.add_table'
SAMFUNDET_CHANGE_TABLE = 'samfundet.change_table'
SAMFUNDET_DELETE_TABLE = 'samfundet.delete_table'
SAMFUNDET_VIEW_TABLE = 'samfundet.view_table'

SAMFUNDET_ADD_TAG = 'samfundet.add_tag'
SAMFUNDET_CHANGE_TAG = 'samfundet.change_tag'
SAMFUNDET_DELETE_TAG = 'samfundet.delete_tag'
SAMFUNDET_VIEW_TAG = 'samfundet.view_tag'

SAMFUNDET_ADD_TEXTITEM = 'samfundet.add_textitem'
SAMFUNDET_CHANGE_TEXTITEM = 'samfundet.change_textitem'
SAMFUNDET_DELETE_TEXTITEM = 'samfundet.delete_textitem'
SAMFUNDET_VIEW_TEXTITEM = 'samfundet.view_textitem'

SAMFUNDET_ADD_USER = 'samfundet.add_user'
SAMFUNDET_CHANGE_USER = 'samfundet.change_user'
SAMFUNDET_DEBUG = 'samfundet.debug'
SAMFUNDET_DELETE_USER = 'samfundet.delete_user'
SAMFUNDET_VIEW_USER = 'samfundet.view_user'

SAMFUNDET_ADD_USERPREFERENCE = 'samfundet.add_userpreference'
SAMFUNDET_CHANGE_USERPREFERENCE = 'samfundet.change_userpreference'
SAMFUNDET_DELETE_USERPREFERENCE = 'samfundet.delete_userpreference'
SAMFUNDET_VIEW_USERPREFERENCE = 'samfundet.view_userpreference'

SAMFUNDET_ADD_VENUE = 'samfundet.add_venue'
SAMFUNDET_CHANGE_VENUE = 'samfundet.change_venue'
SAMFUNDET_DELETE_VENUE = 'samfundet.delete_venue'
SAMFUNDET_VIEW_VENUE = 'samfundet.view_venue'
### End: samfundet ###

### sessions ###
SESSIONS_ADD_SESSION = 'sessions.add_session'
SESSIONS_CHANGE_SESSION = 'sessions.change_session'
SESSIONS_DELETE_SESSION = 'sessions.delete_session'
SESSIONS_VIEW_SESSION = 'sessions.view_session'
