# yapf: disable
"""
THIS FILE IS AUTOGENERATED.
DO NOT WRITE IN THIS FILE, AS IT WILL BE OVERWRITTEN ON NEXT UPDATE.

THIS FILE WAS GENERATED BY: root.management.commands.generate_permissions
LAST UPDATE: 2022-11-14 22:05:51.399916+00:00
"""

############################################################


### admin ###
ADMIN_ADD_LOGENTRY = 'admin.add_logentry'
ADMIN_CHANGE_LOGENTRY = 'admin.change_logentry'
ADMIN_DELETE_LOGENTRY = 'admin.delete_logentry'
ADMIN_VIEW_LOGENTRY = 'admin.view_logentry'
### End: admin ###

### auth ###
AUTH_ADD_GROUP = 'auth.add_group'
AUTH_CHANGE_GROUP = 'auth.change_group'
AUTH_DELETE_GROUP = 'auth.delete_group'
AUTH_VIEW_GROUP = 'auth.view_group'

AUTH_ADD_PERMISSION = 'auth.add_permission'
AUTH_CHANGE_PERMISSION = 'auth.change_permission'
AUTH_DELETE_PERMISSION = 'auth.delete_permission'
AUTH_VIEW_PERMISSION = 'auth.view_permission'

AUTH_ADD_USER = 'auth.add_user'
AUTH_CHANGE_USER = 'auth.change_user'
AUTH_DELETE_USER = 'auth.delete_user'
AUTH_VIEW_USER = 'auth.view_user'
### End: auth ###

### contenttypes ###
CONTENTTYPES_ADD_CONTENTTYPE = 'contenttypes.add_contenttype'
CONTENTTYPES_CHANGE_CONTENTTYPE = 'contenttypes.change_contenttype'
CONTENTTYPES_DELETE_CONTENTTYPE = 'contenttypes.delete_contenttype'
CONTENTTYPES_VIEW_CONTENTTYPE = 'contenttypes.view_contenttype'
### End: contenttypes ###

### guardian ###
GUARDIAN_ADD_GROUPOBJECTPERMISSION = 'guardian.add_groupobjectpermission'
GUARDIAN_CHANGE_GROUPOBJECTPERMISSION = 'guardian.change_groupobjectpermission'
GUARDIAN_DELETE_GROUPOBJECTPERMISSION = 'guardian.delete_groupobjectpermission'
GUARDIAN_VIEW_GROUPOBJECTPERMISSION = 'guardian.view_groupobjectpermission'

GUARDIAN_ADD_USEROBJECTPERMISSION = 'guardian.add_userobjectpermission'
GUARDIAN_CHANGE_USEROBJECTPERMISSION = 'guardian.change_userobjectpermission'
GUARDIAN_DELETE_USEROBJECTPERMISSION = 'guardian.delete_userobjectpermission'
GUARDIAN_VIEW_USEROBJECTPERMISSION = 'guardian.view_userobjectpermission'
### End: guardian ###

### samfundet ###
SAMFUNDET_ADD_EVENT = 'samfundet.add_event'
SAMFUNDET_CHANGE_EVENT = 'samfundet.change_event'
SAMFUNDET_DELETE_EVENT = 'samfundet.delete_event'
SAMFUNDET_VIEW_EVENT = 'samfundet.view_event'

SAMFUNDET_ADD_EVENTGROUP = 'samfundet.add_eventgroup'
SAMFUNDET_CHANGE_EVENTGROUP = 'samfundet.change_eventgroup'
SAMFUNDET_DELETE_EVENTGROUP = 'samfundet.delete_eventgroup'
SAMFUNDET_VIEW_EVENTGROUP = 'samfundet.view_eventgroup'

SAMFUNDET_ADD_VENUE = 'samfundet.add_venue'
SAMFUNDET_CHANGE_VENUE = 'samfundet.change_venue'
SAMFUNDET_DELETE_VENUE = 'samfundet.delete_venue'
SAMFUNDET_VIEW_VENUE = 'samfundet.view_venue'
### End: samfundet ###

### sessions ###
SESSIONS_ADD_SESSION = 'sessions.add_session'
SESSIONS_CHANGE_SESSION = 'sessions.change_session'
SESSIONS_DELETE_SESSION = 'sessions.delete_session'
SESSIONS_VIEW_SESSION = 'sessions.view_session'
