"""
URL patterns for the React frontend.

Generates a Django path for every route in the autogenerated frontend_routes
module (see 'yarn export-routes'), so known frontend routes return 200 and
unknown paths return 404. New frontend routes are picked up automatically.

Routes are served by react_view unless overridden in ROUTE_VIEW_OVERRIDES.
This means if you'd like to add metadata to a specific frontend path, or
have it return a different HTTP response code (for example if the object
isn't found), it needs to be added to ROUTE_VIEW_OVERRIDES.
"""

from __future__ import annotations

from collections.abc import Callable

from django.conf import settings
from django.http import HttpResponse
from django.urls import URLPattern, path
from django.core.exceptions import ImproperlyConfigured

from . import frontend_routes
from .views import react_view, react_404_view, react_event_view

# Routes that need a custom view, keyed by frontend_routes.py constant name.
ROUTE_VIEW_OVERRIDES: dict[str, Callable[..., HttpResponse]] = {
    'EVENT': react_event_view,
}


def _iter_frontend_routes() -> list[tuple[str, str]]:
    """Yield (constant_name, route) for every route defined in frontend_routes."""
    routes: list[tuple[str, str]] = []
    for name, value in vars(frontend_routes).items():
        if name.startswith('_') or not isinstance(value, str):
            continue
        routes.append((name, value))
    return routes


def _validate_overrides(route_names: set[str]) -> None:
    """Raise exception if ROUTE_VIEW_OVERRIDES contains a key which is not a valid frontend route."""
    unknown = ROUTE_VIEW_OVERRIDES.keys() - route_names
    if unknown:
        raise ImproperlyConfigured(
            f'ROUTE_VIEW_OVERRIDES contains unknown frontend route(s): {sorted(unknown)}. Keys must be constant names from frontend_routes.py.'
        )


def _build_patterns() -> list[URLPattern]:
    patterns: list[URLPattern] = []
    routes = _iter_frontend_routes()
    _validate_overrides({name for name, _ in routes})

    for name, route in routes:
        view = ROUTE_VIEW_OVERRIDES.get(name, react_view)
        url_name = f'{settings.REACT_ROUTE_PREFIX}_{name.lower()}'

        # Register with and without trailing slash, so e.g. both '/gangs' and '/gangs/' work.
        clean = route.strip('/')
        patterns.append(path(clean, view, name=url_name))
        if clean:
            patterns.append(path(f'{clean}/', view, name=f'{url_name}_slash'))

    # Catch-all (must be defined last)
    # Unknown paths get the React not-found page with HTTP 404.
    patterns.append(path('<path:resource>', react_404_view))

    return patterns


urlpatterns = _build_patterns()
