/**
"""
THIS FILE IS AUTOGENERATED.
DO NOT WRITE IN THIS FILE, AS IT WILL BE OVERWRITTEN ON NEXT UPDATE.

THIS FILE WAS GENERATED BY: root.management.commands.generate_permissions
"""
*/

// ############################################################

// ### admin ###
export const ADMIN_ADD_LOGENTRY = 'admin.add_logentry';
export const ADMIN_CHANGE_LOGENTRY = 'admin.change_logentry';
export const ADMIN_DELETE_LOGENTRY = 'admin.delete_logentry';
export const ADMIN_VIEW_LOGENTRY = 'admin.view_logentry';
// ### End: admin ###

// ### auth ###
export const AUTH_ADD_GROUP = 'auth.add_group';
export const AUTH_CHANGE_GROUP = 'auth.change_group';
export const AUTH_DELETE_GROUP = 'auth.delete_group';
export const AUTH_VIEW_GROUP = 'auth.view_group';

export const AUTH_ADD_PERMISSION = 'auth.add_permission';
export const AUTH_CHANGE_PERMISSION = 'auth.change_permission';
export const AUTH_DELETE_PERMISSION = 'auth.delete_permission';
export const AUTH_VIEW_PERMISSION = 'auth.view_permission';
// ### End: auth ###

// ### contenttypes ###
export const CONTENTTYPES_ADD_CONTENTTYPE = 'contenttypes.add_contenttype';
export const CONTENTTYPES_CHANGE_CONTENTTYPE = 'contenttypes.change_contenttype';
export const CONTENTTYPES_DELETE_CONTENTTYPE = 'contenttypes.delete_contenttype';
export const CONTENTTYPES_VIEW_CONTENTTYPE = 'contenttypes.view_contenttype';
// ### End: contenttypes ###

// ### guardian ###
export const GUARDIAN_ADD_GROUPOBJECTPERMISSION = 'guardian.add_groupobjectpermission';
export const GUARDIAN_CHANGE_GROUPOBJECTPERMISSION = 'guardian.change_groupobjectpermission';
export const GUARDIAN_DELETE_GROUPOBJECTPERMISSION = 'guardian.delete_groupobjectpermission';
export const GUARDIAN_VIEW_GROUPOBJECTPERMISSION = 'guardian.view_groupobjectpermission';

export const GUARDIAN_ADD_USEROBJECTPERMISSION = 'guardian.add_userobjectpermission';
export const GUARDIAN_CHANGE_USEROBJECTPERMISSION = 'guardian.change_userobjectpermission';
export const GUARDIAN_DELETE_USEROBJECTPERMISSION = 'guardian.delete_userobjectpermission';
export const GUARDIAN_VIEW_USEROBJECTPERMISSION = 'guardian.view_userobjectpermission';
// ### End: guardian ###

// ### samfundet ###
export const SAMFUNDET_ADD_BILLIGEVENT = 'samfundet.add_billigevent';
export const SAMFUNDET_CHANGE_BILLIGEVENT = 'samfundet.change_billigevent';
export const SAMFUNDET_DELETE_BILLIGEVENT = 'samfundet.delete_billigevent';
export const SAMFUNDET_VIEW_BILLIGEVENT = 'samfundet.view_billigevent';

export const SAMFUNDET_ADD_BILLIGPRICEGROUP = 'samfundet.add_billigpricegroup';
export const SAMFUNDET_CHANGE_BILLIGPRICEGROUP = 'samfundet.change_billigpricegroup';
export const SAMFUNDET_DELETE_BILLIGPRICEGROUP = 'samfundet.delete_billigpricegroup';
export const SAMFUNDET_VIEW_BILLIGPRICEGROUP = 'samfundet.view_billigpricegroup';

export const SAMFUNDET_ADD_BILLIGTICKETGROUP = 'samfundet.add_billigticketgroup';
export const SAMFUNDET_CHANGE_BILLIGTICKETGROUP = 'samfundet.change_billigticketgroup';
export const SAMFUNDET_DELETE_BILLIGTICKETGROUP = 'samfundet.delete_billigticketgroup';
export const SAMFUNDET_VIEW_BILLIGTICKETGROUP = 'samfundet.view_billigticketgroup';

export const SAMFUNDET_ADD_BLOGPOST = 'samfundet.add_blogpost';
export const SAMFUNDET_CHANGE_BLOGPOST = 'samfundet.change_blogpost';
export const SAMFUNDET_DELETE_BLOGPOST = 'samfundet.delete_blogpost';
export const SAMFUNDET_VIEW_BLOGPOST = 'samfundet.view_blogpost';

export const SAMFUNDET_ADD_BOOKING = 'samfundet.add_booking';
export const SAMFUNDET_CHANGE_BOOKING = 'samfundet.change_booking';
export const SAMFUNDET_DELETE_BOOKING = 'samfundet.delete_booking';
export const SAMFUNDET_VIEW_BOOKING = 'samfundet.view_booking';

export const SAMFUNDET_ADD_CAMPUS = 'samfundet.add_campus';
export const SAMFUNDET_CHANGE_CAMPUS = 'samfundet.change_campus';
export const SAMFUNDET_DELETE_CAMPUS = 'samfundet.delete_campus';
export const SAMFUNDET_VIEW_CAMPUS = 'samfundet.view_campus';

export const SAMFUNDET_ADD_CLOSEDPERIOD = 'samfundet.add_closedperiod';
export const SAMFUNDET_CHANGE_CLOSEDPERIOD = 'samfundet.change_closedperiod';
export const SAMFUNDET_DELETE_CLOSEDPERIOD = 'samfundet.delete_closedperiod';
export const SAMFUNDET_VIEW_CLOSEDPERIOD = 'samfundet.view_closedperiod';

export const SAMFUNDET_ADD_EVENT = 'samfundet.add_event';
export const SAMFUNDET_CHANGE_EVENT = 'samfundet.change_event';
export const SAMFUNDET_DELETE_EVENT = 'samfundet.delete_event';
export const SAMFUNDET_VIEW_EVENT = 'samfundet.view_event';

export const SAMFUNDET_ADD_EVENTCUSTOMTICKET = 'samfundet.add_eventcustomticket';
export const SAMFUNDET_CHANGE_EVENTCUSTOMTICKET = 'samfundet.change_eventcustomticket';
export const SAMFUNDET_DELETE_EVENTCUSTOMTICKET = 'samfundet.delete_eventcustomticket';
export const SAMFUNDET_VIEW_EVENTCUSTOMTICKET = 'samfundet.view_eventcustomticket';

export const SAMFUNDET_ADD_EVENTGROUP = 'samfundet.add_eventgroup';
export const SAMFUNDET_CHANGE_EVENTGROUP = 'samfundet.change_eventgroup';
export const SAMFUNDET_DELETE_EVENTGROUP = 'samfundet.delete_eventgroup';
export const SAMFUNDET_VIEW_EVENTGROUP = 'samfundet.view_eventgroup';

export const SAMFUNDET_ADD_EVENTREGISTRATION = 'samfundet.add_eventregistration';
export const SAMFUNDET_CHANGE_EVENTREGISTRATION = 'samfundet.change_eventregistration';
export const SAMFUNDET_DELETE_EVENTREGISTRATION = 'samfundet.delete_eventregistration';
export const SAMFUNDET_VIEW_EVENTREGISTRATION = 'samfundet.view_eventregistration';

export const SAMFUNDET_ADD_FOODCATEGORY = 'samfundet.add_foodcategory';
export const SAMFUNDET_CHANGE_FOODCATEGORY = 'samfundet.change_foodcategory';
export const SAMFUNDET_DELETE_FOODCATEGORY = 'samfundet.delete_foodcategory';
export const SAMFUNDET_VIEW_FOODCATEGORY = 'samfundet.view_foodcategory';

export const SAMFUNDET_ADD_FOODPREFERENCE = 'samfundet.add_foodpreference';
export const SAMFUNDET_CHANGE_FOODPREFERENCE = 'samfundet.change_foodpreference';
export const SAMFUNDET_DELETE_FOODPREFERENCE = 'samfundet.delete_foodpreference';
export const SAMFUNDET_VIEW_FOODPREFERENCE = 'samfundet.view_foodpreference';

export const SAMFUNDET_ADD_GANG = 'samfundet.add_gang';
export const SAMFUNDET_CHANGE_GANG = 'samfundet.change_gang';
export const SAMFUNDET_DELETE_GANG = 'samfundet.delete_gang';
export const SAMFUNDET_VIEW_GANG = 'samfundet.view_gang';

export const SAMFUNDET_ADD_GANGSECTION = 'samfundet.add_gangsection';
export const SAMFUNDET_CHANGE_GANGSECTION = 'samfundet.change_gangsection';
export const SAMFUNDET_DELETE_GANGSECTION = 'samfundet.delete_gangsection';
export const SAMFUNDET_VIEW_GANGSECTION = 'samfundet.view_gangsection';

export const SAMFUNDET_ADD_GANGTYPE = 'samfundet.add_gangtype';
export const SAMFUNDET_CHANGE_GANGTYPE = 'samfundet.change_gangtype';
export const SAMFUNDET_DELETE_GANGTYPE = 'samfundet.delete_gangtype';
export const SAMFUNDET_VIEW_GANGTYPE = 'samfundet.view_gangtype';

export const SAMFUNDET_ADD_IMAGE = 'samfundet.add_image';
export const SAMFUNDET_CHANGE_IMAGE = 'samfundet.change_image';
export const SAMFUNDET_DELETE_IMAGE = 'samfundet.delete_image';
export const SAMFUNDET_VIEW_IMAGE = 'samfundet.view_image';

export const SAMFUNDET_ADD_INFOBOX = 'samfundet.add_infobox';
export const SAMFUNDET_CHANGE_INFOBOX = 'samfundet.change_infobox';
export const SAMFUNDET_DELETE_INFOBOX = 'samfundet.delete_infobox';
export const SAMFUNDET_VIEW_INFOBOX = 'samfundet.view_infobox';

export const SAMFUNDET_ADD_INFORMATIONPAGE = 'samfundet.add_informationpage';
export const SAMFUNDET_CHANGE_INFORMATIONPAGE = 'samfundet.change_informationpage';
export const SAMFUNDET_DELETE_INFORMATIONPAGE = 'samfundet.delete_informationpage';
export const SAMFUNDET_VIEW_INFORMATIONPAGE = 'samfundet.view_informationpage';

export const SAMFUNDET_ADD_INTERVIEW = 'samfundet.add_interview';
export const SAMFUNDET_CHANGE_INTERVIEW = 'samfundet.change_interview';
export const SAMFUNDET_DELETE_INTERVIEW = 'samfundet.delete_interview';
export const SAMFUNDET_VIEW_INTERVIEW = 'samfundet.view_interview';

export const SAMFUNDET_ADD_INTERVIEWROOM = 'samfundet.add_interviewroom';
export const SAMFUNDET_CHANGE_INTERVIEWROOM = 'samfundet.change_interviewroom';
export const SAMFUNDET_DELETE_INTERVIEWROOM = 'samfundet.delete_interviewroom';
export const SAMFUNDET_VIEW_INTERVIEWROOM = 'samfundet.view_interviewroom';

export const SAMFUNDET_ADD_KEYVALUE = 'samfundet.add_keyvalue';
export const SAMFUNDET_CHANGE_KEYVALUE = 'samfundet.change_keyvalue';
export const SAMFUNDET_DELETE_KEYVALUE = 'samfundet.delete_keyvalue';
export const SAMFUNDET_VIEW_KEYVALUE = 'samfundet.view_keyvalue';

export const SAMFUNDET_ADD_MENU = 'samfundet.add_menu';
export const SAMFUNDET_CHANGE_MENU = 'samfundet.change_menu';
export const SAMFUNDET_DELETE_MENU = 'samfundet.delete_menu';
export const SAMFUNDET_VIEW_MENU = 'samfundet.view_menu';

export const SAMFUNDET_ADD_MENUITEM = 'samfundet.add_menuitem';
export const SAMFUNDET_CHANGE_MENUITEM = 'samfundet.change_menuitem';
export const SAMFUNDET_DELETE_MENUITEM = 'samfundet.delete_menuitem';
export const SAMFUNDET_VIEW_MENUITEM = 'samfundet.view_menuitem';

export const SAMFUNDET_ADD_MERCH = 'samfundet.add_merch';
export const SAMFUNDET_CHANGE_MERCH = 'samfundet.change_merch';
export const SAMFUNDET_DELETE_MERCH = 'samfundet.delete_merch';
export const SAMFUNDET_VIEW_MERCH = 'samfundet.view_merch';

export const SAMFUNDET_ADD_MERCHVARIATION = 'samfundet.add_merchvariation';
export const SAMFUNDET_CHANGE_MERCHVARIATION = 'samfundet.change_merchvariation';
export const SAMFUNDET_DELETE_MERCHVARIATION = 'samfundet.delete_merchvariation';
export const SAMFUNDET_VIEW_MERCHVARIATION = 'samfundet.view_merchvariation';

export const SAMFUNDET_ADD_NONMEMBEREMAILREGISTRATION = 'samfundet.add_nonmemberemailregistration';
export const SAMFUNDET_CHANGE_NONMEMBEREMAILREGISTRATION = 'samfundet.change_nonmemberemailregistration';
export const SAMFUNDET_DELETE_NONMEMBEREMAILREGISTRATION = 'samfundet.delete_nonmemberemailregistration';
export const SAMFUNDET_VIEW_NONMEMBEREMAILREGISTRATION = 'samfundet.view_nonmemberemailregistration';

export const SAMFUNDET_ADD_NOTIFICATION = 'samfundet.add_notification';
export const SAMFUNDET_CHANGE_NOTIFICATION = 'samfundet.change_notification';
export const SAMFUNDET_DELETE_NOTIFICATION = 'samfundet.delete_notification';
export const SAMFUNDET_VIEW_NOTIFICATION = 'samfundet.view_notification';

export const SAMFUNDET_ADD_OCCUPIEDTIMESLOT = 'samfundet.add_occupiedtimeslot';
export const SAMFUNDET_CHANGE_OCCUPIEDTIMESLOT = 'samfundet.change_occupiedtimeslot';
export const SAMFUNDET_DELETE_OCCUPIEDTIMESLOT = 'samfundet.delete_occupiedtimeslot';
export const SAMFUNDET_VIEW_OCCUPIEDTIMESLOT = 'samfundet.view_occupiedtimeslot';

export const SAMFUNDET_ADD_ORGANIZATION = 'samfundet.add_organization';
export const SAMFUNDET_CHANGE_ORGANIZATION = 'samfundet.change_organization';
export const SAMFUNDET_DELETE_ORGANIZATION = 'samfundet.delete_organization';
export const SAMFUNDET_VIEW_ORGANIZATION = 'samfundet.view_organization';

export const SAMFUNDET_ADD_PROFILE = 'samfundet.add_profile';
export const SAMFUNDET_CHANGE_PROFILE = 'samfundet.change_profile';
export const SAMFUNDET_DELETE_PROFILE = 'samfundet.delete_profile';
export const SAMFUNDET_VIEW_PROFILE = 'samfundet.view_profile';

export const SAMFUNDET_ADD_RECRUITMENT = 'samfundet.add_recruitment';
export const SAMFUNDET_CHANGE_RECRUITMENT = 'samfundet.change_recruitment';
export const SAMFUNDET_DELETE_RECRUITMENT = 'samfundet.delete_recruitment';
export const SAMFUNDET_VIEW_RECRUITMENT = 'samfundet.view_recruitment';

export const SAMFUNDET_ADD_RECRUITMENTAPPLICATION = 'samfundet.add_recruitmentapplication';
export const SAMFUNDET_CHANGE_RECRUITMENTAPPLICATION = 'samfundet.change_recruitmentapplication';
export const SAMFUNDET_DELETE_RECRUITMENTAPPLICATION = 'samfundet.delete_recruitmentapplication';
export const SAMFUNDET_VIEW_RECRUITMENTAPPLICATION = 'samfundet.view_recruitmentapplication';

export const SAMFUNDET_ADD_RECRUITMENTCAMPUSSTAT = 'samfundet.add_recruitmentcampusstat';
export const SAMFUNDET_CHANGE_RECRUITMENTCAMPUSSTAT = 'samfundet.change_recruitmentcampusstat';
export const SAMFUNDET_DELETE_RECRUITMENTCAMPUSSTAT = 'samfundet.delete_recruitmentcampusstat';
export const SAMFUNDET_VIEW_RECRUITMENTCAMPUSSTAT = 'samfundet.view_recruitmentcampusstat';

export const SAMFUNDET_ADD_RECRUITMENTDATESTAT = 'samfundet.add_recruitmentdatestat';
export const SAMFUNDET_CHANGE_RECRUITMENTDATESTAT = 'samfundet.change_recruitmentdatestat';
export const SAMFUNDET_DELETE_RECRUITMENTDATESTAT = 'samfundet.delete_recruitmentdatestat';
export const SAMFUNDET_VIEW_RECRUITMENTDATESTAT = 'samfundet.view_recruitmentdatestat';

export const SAMFUNDET_ADD_RECRUITMENTINTERVIEWAVAILABILITY = 'samfundet.add_recruitmentinterviewavailability';
export const SAMFUNDET_CHANGE_RECRUITMENTINTERVIEWAVAILABILITY = 'samfundet.change_recruitmentinterviewavailability';
export const SAMFUNDET_DELETE_RECRUITMENTINTERVIEWAVAILABILITY = 'samfundet.delete_recruitmentinterviewavailability';
export const SAMFUNDET_VIEW_RECRUITMENTINTERVIEWAVAILABILITY = 'samfundet.view_recruitmentinterviewavailability';

export const SAMFUNDET_ADD_RECRUITMENTPOSITION = 'samfundet.add_recruitmentposition';
export const SAMFUNDET_CHANGE_RECRUITMENTPOSITION = 'samfundet.change_recruitmentposition';
export const SAMFUNDET_DELETE_RECRUITMENTPOSITION = 'samfundet.delete_recruitmentposition';
export const SAMFUNDET_VIEW_RECRUITMENTPOSITION = 'samfundet.view_recruitmentposition';

export const SAMFUNDET_ADD_RECRUITMENTSEPERATEPOSITION = 'samfundet.add_recruitmentseparateposition';
export const SAMFUNDET_CHANGE_RECRUITMENTSEPERATEPOSITION = 'samfundet.change_recruitmentseparateposition';
export const SAMFUNDET_DELETE_RECRUITMENTSEPERATEPOSITION = 'samfundet.delete_recruitmentseparateposition';
export const SAMFUNDET_VIEW_RECRUITMENTSEPERATEPOSITION = 'samfundet.view_recruitmentseparateposition';

export const SAMFUNDET_ADD_RECRUITMENTSTATISTICS = 'samfundet.add_recruitmentstatistics';
export const SAMFUNDET_CHANGE_RECRUITMENTSTATISTICS = 'samfundet.change_recruitmentstatistics';
export const SAMFUNDET_DELETE_RECRUITMENTSTATISTICS = 'samfundet.delete_recruitmentstatistics';
export const SAMFUNDET_VIEW_RECRUITMENTSTATISTICS = 'samfundet.view_recruitmentstatistics';

export const SAMFUNDET_ADD_RECRUITMENTTIMESTAT = 'samfundet.add_recruitmenttimestat';
export const SAMFUNDET_CHANGE_RECRUITMENTTIMESTAT = 'samfundet.change_recruitmenttimestat';
export const SAMFUNDET_DELETE_RECRUITMENTTIMESTAT = 'samfundet.delete_recruitmenttimestat';
export const SAMFUNDET_VIEW_RECRUITMENTTIMESTAT = 'samfundet.view_recruitmenttimestat';

export const SAMFUNDET_ADD_RESERVATION = 'samfundet.add_reservation';
export const SAMFUNDET_CHANGE_RESERVATION = 'samfundet.change_reservation';
export const SAMFUNDET_DELETE_RESERVATION = 'samfundet.delete_reservation';
export const SAMFUNDET_VIEW_RESERVATION = 'samfundet.view_reservation';

export const SAMFUNDET_ADD_SAKSDOKUMENT = 'samfundet.add_saksdokument';
export const SAMFUNDET_CHANGE_SAKSDOKUMENT = 'samfundet.change_saksdokument';
export const SAMFUNDET_DELETE_SAKSDOKUMENT = 'samfundet.delete_saksdokument';
export const SAMFUNDET_VIEW_SAKSDOKUMENT = 'samfundet.view_saksdokument';

export const SAMFUNDET_ADD_TABLE = 'samfundet.add_table';
export const SAMFUNDET_CHANGE_TABLE = 'samfundet.change_table';
export const SAMFUNDET_DELETE_TABLE = 'samfundet.delete_table';
export const SAMFUNDET_VIEW_TABLE = 'samfundet.view_table';

export const SAMFUNDET_ADD_TAG = 'samfundet.add_tag';
export const SAMFUNDET_CHANGE_TAG = 'samfundet.change_tag';
export const SAMFUNDET_DELETE_TAG = 'samfundet.delete_tag';
export const SAMFUNDET_VIEW_TAG = 'samfundet.view_tag';

export const SAMFUNDET_ADD_TEXTITEM = 'samfundet.add_textitem';
export const SAMFUNDET_CHANGE_TEXTITEM = 'samfundet.change_textitem';
export const SAMFUNDET_DELETE_TEXTITEM = 'samfundet.delete_textitem';
export const SAMFUNDET_VIEW_TEXTITEM = 'samfundet.view_textitem';

export const SAMFUNDET_ADD_USER = 'samfundet.add_user';
export const SAMFUNDET_CHANGE_USER = 'samfundet.change_user';
export const SAMFUNDET_DEBUG = 'samfundet.debug';
export const SAMFUNDET_DELETE_USER = 'samfundet.delete_user';
export const SAMFUNDET_IMPERSONATE = 'samfundet.impersonate';
export const SAMFUNDET_VIEW_USER = 'samfundet.view_user';

export const SAMFUNDET_ADD_USERFEEDBACKMODEL = 'samfundet.add_userfeedbackmodel';
export const SAMFUNDET_CHANGE_USERFEEDBACKMODEL = 'samfundet.change_userfeedbackmodel';
export const SAMFUNDET_DELETE_USERFEEDBACKMODEL = 'samfundet.delete_userfeedbackmodel';
export const SAMFUNDET_VIEW_USERFEEDBACKMODEL = 'samfundet.view_userfeedbackmodel';

export const SAMFUNDET_ADD_USERPREFERENCE = 'samfundet.add_userpreference';
export const SAMFUNDET_CHANGE_USERPREFERENCE = 'samfundet.change_userpreference';
export const SAMFUNDET_DELETE_USERPREFERENCE = 'samfundet.delete_userpreference';
export const SAMFUNDET_VIEW_USERPREFERENCE = 'samfundet.view_userpreference';

export const SAMFUNDET_ADD_VENUE = 'samfundet.add_venue';
export const SAMFUNDET_CHANGE_VENUE = 'samfundet.change_venue';
export const SAMFUNDET_DELETE_VENUE = 'samfundet.delete_venue';
export const SAMFUNDET_VIEW_VENUE = 'samfundet.view_venue';
// ### End: samfundet ###

// ### sessions ###
export const SESSIONS_ADD_SESSION = 'sessions.add_session';
export const SESSIONS_CHANGE_SESSION = 'sessions.change_session';
export const SESSIONS_DELETE_SESSION = 'sessions.delete_session';
export const SESSIONS_VIEW_SESSION = 'sessions.view_session';
