/**
"""
THIS FILE IS AUTOGENERATED.
DO NOT WRITE IN THIS FILE, AS IT WILL BE OVERWRITTEN ON NEXT UPDATE.

THIS FILE WAS GENERATED BY: root.management.commands.generate_permissions
LAST UPDATE: 2022-11-26 13:15:35.414920+00:00
"""
*/

// ############################################################

// ### admin ###
export const ADMIN_ADD_LOGENTRY = 'admin.add_logentry';
export const ADMIN_CHANGE_LOGENTRY = 'admin.change_logentry';
export const ADMIN_DELETE_LOGENTRY = 'admin.delete_logentry';
export const ADMIN_VIEW_LOGENTRY = 'admin.view_logentry';
// ### End: admin ###

// ### auth ###
export const AUTH_ADD_GROUP = 'auth.add_group';
export const AUTH_CHANGE_GROUP = 'auth.change_group';
export const AUTH_DELETE_GROUP = 'auth.delete_group';
export const AUTH_VIEW_GROUP = 'auth.view_group';

export const AUTH_ADD_PERMISSION = 'auth.add_permission';
export const AUTH_CHANGE_PERMISSION = 'auth.change_permission';
export const AUTH_DELETE_PERMISSION = 'auth.delete_permission';
export const AUTH_VIEW_PERMISSION = 'auth.view_permission';

export const AUTH_ADD_USER = 'auth.add_user';
export const AUTH_CHANGE_USER = 'auth.change_user';
export const AUTH_DELETE_USER = 'auth.delete_user';
export const AUTH_VIEW_USER = 'auth.view_user';
// ### End: auth ###

// ### contenttypes ###
export const CONTENTTYPES_ADD_CONTENTTYPE = 'contenttypes.add_contenttype';
export const CONTENTTYPES_CHANGE_CONTENTTYPE = 'contenttypes.change_contenttype';
export const CONTENTTYPES_DELETE_CONTENTTYPE = 'contenttypes.delete_contenttype';
export const CONTENTTYPES_VIEW_CONTENTTYPE = 'contenttypes.view_contenttype';
// ### End: contenttypes ###

// ### guardian ###
export const GUARDIAN_ADD_GROUPOBJECTPERMISSION = 'guardian.add_groupobjectpermission';
export const GUARDIAN_CHANGE_GROUPOBJECTPERMISSION = 'guardian.change_groupobjectpermission';
export const GUARDIAN_DELETE_GROUPOBJECTPERMISSION = 'guardian.delete_groupobjectpermission';
export const GUARDIAN_VIEW_GROUPOBJECTPERMISSION = 'guardian.view_groupobjectpermission';

export const GUARDIAN_ADD_USEROBJECTPERMISSION = 'guardian.add_userobjectpermission';
export const GUARDIAN_CHANGE_USEROBJECTPERMISSION = 'guardian.change_userobjectpermission';
export const GUARDIAN_DELETE_USEROBJECTPERMISSION = 'guardian.delete_userobjectpermission';
export const GUARDIAN_VIEW_USEROBJECTPERMISSION = 'guardian.view_userobjectpermission';
// ### End: guardian ###

// ### samfundet ###
export const SAMFUNDET_ADD_EVENT = 'samfundet.add_event';
export const SAMFUNDET_CHANGE_EVENT = 'samfundet.change_event';
export const SAMFUNDET_DELETE_EVENT = 'samfundet.delete_event';
export const SAMFUNDET_VIEW_EVENT = 'samfundet.view_event';

export const SAMFUNDET_ADD_EVENTGROUP = 'samfundet.add_eventgroup';
export const SAMFUNDET_CHANGE_EVENTGROUP = 'samfundet.change_eventgroup';
export const SAMFUNDET_DELETE_EVENTGROUP = 'samfundet.delete_eventgroup';
export const SAMFUNDET_VIEW_EVENTGROUP = 'samfundet.view_eventgroup';

export const SAMFUNDET_ADD_GANG = 'samfundet.add_gang';
export const SAMFUNDET_CHANGE_GANG = 'samfundet.change_gang';
export const SAMFUNDET_DELETE_GANG = 'samfundet.delete_gang';
export const SAMFUNDET_VIEW_GANG = 'samfundet.view_gang';

export const SAMFUNDET_ADD_GANGTYPE = 'samfundet.add_gangtype';
export const SAMFUNDET_CHANGE_GANGTYPE = 'samfundet.change_gangtype';
export const SAMFUNDET_DELETE_GANGTYPE = 'samfundet.delete_gangtype';
export const SAMFUNDET_VIEW_GANGTYPE = 'samfundet.view_gangtype';

export const SAMFUNDET_ADD_INFORMATIONPAGE = 'samfundet.add_informationpage';
export const SAMFUNDET_CHANGE_INFORMATIONPAGE = 'samfundet.change_informationpage';
export const SAMFUNDET_DELETE_INFORMATIONPAGE = 'samfundet.delete_informationpage';
export const SAMFUNDET_VIEW_INFORMATIONPAGE = 'samfundet.view_informationpage';

export const SAMFUNDET_ADD_PROFILE = 'samfundet.add_profile';
export const SAMFUNDET_CHANGE_PROFILE = 'samfundet.change_profile';
export const SAMFUNDET_DELETE_PROFILE = 'samfundet.delete_profile';
export const SAMFUNDET_VIEW_PROFILE = 'samfundet.view_profile';

export const SAMFUNDET_ADD_USERPREFERENCE = 'samfundet.add_userpreference';
export const SAMFUNDET_CHANGE_USERPREFERENCE = 'samfundet.change_userpreference';
export const SAMFUNDET_DELETE_USERPREFERENCE = 'samfundet.delete_userpreference';
export const SAMFUNDET_VIEW_USERPREFERENCE = 'samfundet.view_userpreference';

export const SAMFUNDET_ADD_VENUE = 'samfundet.add_venue';
export const SAMFUNDET_CHANGE_VENUE = 'samfundet.change_venue';
export const SAMFUNDET_DELETE_VENUE = 'samfundet.delete_venue';
export const SAMFUNDET_VIEW_VENUE = 'samfundet.view_venue';
// ### End: samfundet ###

// ### sessions ###
export const SESSIONS_ADD_SESSION = 'sessions.add_session';
export const SESSIONS_CHANGE_SESSION = 'sessions.change_session';
export const SESSIONS_DELETE_SESSION = 'sessions.delete_session';
export const SESSIONS_VIEW_SESSION = 'sessions.view_session';
