# Generated by Django 5.0.1 on 2024-01-16 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samfundet", "0007_remove_foodcategory_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (norsk)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Navn (engelsk)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FoodCategory",
                "verbose_name_plural": "FoodCategories",
            },
        ),
        migrations.CreateModel(
            name="FoodPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (norsk)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Navn (engelsk)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FoodPreference",
                "verbose_name_plural": "FoodPreferences",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (norsk)",
                    ),
                ),
                (
                    "description_nb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beskrivelse (norsk)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Navn (engelsk)",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beskrivelse (engelsk)"
                    ),
                ),
                ("price", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "price_member",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sulten.foodcategory",
                    ),
                ),
                (
                    "food_preferences",
                    models.ManyToManyField(blank=True, to="sulten.foodpreference"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "MenuItem", "verbose_name_plural": "MenuItems",},
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (norsk)",
                    ),
                ),
                (
                    "description_nb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beskrivelse (norsk)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Navn (engelsk)",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beskrivelse (engelsk)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_items",
                    models.ManyToManyField(blank=True, to="sulten.menuitem"),
                ),
            ],
            options={"verbose_name": "Menu", "verbose_name_plural": "Menus",},
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (norsk)",
                    ),
                ),
                (
                    "description_nb",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Beskrivelse (norsk)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Navn (engelsk)",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Beskrivelse (engelsk)",
                    ),
                ),
                ("seating", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samfundet.venue",
                    ),
                ),
            ],
            options={"verbose_name": "Table", "verbose_name_plural": "Tables",},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=64, verbose_name="Navn"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=64, verbose_name="Epost"),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Telefonnummer",
                    ),
                ),
                ("reservation_date", models.DateField(blank=True, verbose_name="Dato")),
                ("start_time", models.TimeField(blank=True, verbose_name="Starttid")),
                ("end_time", models.TimeField(blank=True, verbose_name="Sluttid")),
                (
                    "occasion",
                    models.CharField(
                        choices=[("DRINK", "Drikke"), ("FOOD", "Mat")],
                        default="FOOD",
                        max_length=24,
                    ),
                ),
                (
                    "guest_count",
                    models.PositiveSmallIntegerField(verbose_name="Antall gjester"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tilleggsinformasjon"
                    ),
                ),
                (
                    "internal_messages",
                    models.TextField(
                        blank=True, null=True, verbose_name="Interne meldinger"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samfundet.venue",
                        verbose_name="Sted",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sulten.table",
                        verbose_name="Bord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("from_dt", models.DateTimeField(blank=True, null=True)),
                ("to_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "phone_nr",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tables", models.ManyToManyField(blank=True, to="sulten.table")),
            ],
            options={"verbose_name": "Booking", "verbose_name_plural": "Bookings",},
        ),
    ]
