# Generated by Django 5.0.1 on 2024-01-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sulten", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="created_by",),
        migrations.RemoveField(model_name="reservation", name="table",),
        migrations.RemoveField(model_name="reservation", name="updated_by",),
        migrations.RemoveField(model_name="reservation", name="user",),
        migrations.RemoveField(model_name="reservation", name="venue",),
        migrations.RemoveField(model_name="table", name="created_by",),
        migrations.RemoveField(model_name="table", name="updated_by",),
        migrations.RemoveField(model_name="table", name="venue",),
        migrations.DeleteModel(name="Booking",),
        migrations.DeleteModel(name="Reservation",),
        migrations.DeleteModel(name="Table",),
    ]
